-- ---------------------------------------------------------------
-- CRM NEW 4 VIEWS CATCRM_CUSTOMER_FOCUS, CATCRM_CUSTOMER_GROUP, 
--              .. CATCRM_CUSTOMER_TYPE CATCRM_CUSTOMER_SEGMENT
-- ADD 2 COLUMN FOR V_CATCRM_BILLING_PROFILE
-- ---------------------------------------------------------------
-- NEW VIEW.
CREATE TABLE CRMDATA.CATCRM_CUSTOMER_FOCUS
(
CODE      VARCHAR2(255) NOT NULL,  
TEXT      VARCHAR2(255) NOT NULL, 
LISTORDER NUMBER(38) NOT NULL
);
-- NEW VIEW.
CREATE TABLE CRMDATA.CATCRM_CUSTOMER_GROUP
(
CODE      VARCHAR2(255) NOT NULL,  
TEXT      VARCHAR2(255) NOT NULL, 
LISTORDER NUMBER(38) NOT NULL
);
-- NEW VIEW.
CREATE TABLE CRMDATA.CATCRM_CUSTOMER_TYPE
(
CODE      VARCHAR2(255) NOT NULL,  
TEXT      VARCHAR2(255) NOT NULL, 
LISTORDER NUMBER(38) NOT NULL
);
-- NEW VIEW.
CREATE TABLE CRMDATA.CATCRM_CUSTOMER_SEGMENT
(
CODE      VARCHAR2(255) NOT NULL,  
TEXT      VARCHAR2(255) NOT NULL, 
LISTORDER NUMBER(38) NOT NULL
);
-- ADD COLUMN.
ALTER TABLE CRMDATA.V_CATCRM_BILLING_PROFILE ADD 
( 
VAT_TYPE VARCHAR2(255 BYTE),
CURRENCY VARCHAR2(100 BYTE),
CAT_COLLECTION_UNIT VARCHAR2(100 BYTE)
);
-- DATA FOR CATCRM_CUSTOMER_SEGMENT
INSERT INTO CRMDATA.CATCRM_CUSTOMER_SEGMENT VALUES('1', 'ธุรกิจทั่วไป', '1');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_SEGMENT VALUES('2', 'หน่วยงานรัฐ', '2');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_SEGMENT VALUES('3', 'บุคคลทั่วไป', '3');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_SEGMENT VALUES('4', 'Carrier/Operator/NON POTs', '4');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_SEGMENT VALUES('5', '"Mkt.Arm"', '5');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_SEGMENT VALUES('6', 'ISP', '6');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_SEGMENT VALUES('7', 'Reseller/Agent', '7');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_SEGMENT VALUES('8', 'ธุรกิจ กสท', '8');
-- -------------------------------
-- DATA FOR CATCRM_CUSTOMER_TYPE
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('0', 'อื่น ๆ', '1');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('101', 'ธุรกิจการเกษตร', '2');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('102', 'อาหารและเครื่องดื่ม', '3');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('201', 'แฟชั่น (ผู้ผลิต/ออกแบบ/ตัวแทนจำหน่าย)', '4');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('202', 'ของใช้ภายในบ้านและสำนักงาน (ผู้ผลิตและตัวแทนจำหน่าย)', '5');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('203', 'ของใช้ส่วนตัวและเวชภัณฑ์ (ผู้ผลิตและตัวแทนจำหน่าย)', '6');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('301', 'ธนาคาร', '7');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('302', 'เงินทุนและหลักทรัพย์', '8');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('303', 'ประกันภัยและประกันชีวิต', '9');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('401', 'ยานยนต์', '10');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('402', 'วัสดุอุตสาหกรรมและเครื่องจักร', '11');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('403', 'บรรจุภัณฑ์', '12');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('404', 'กระดาษและวัสดุการพิมพ์ (ผู้ผลิตและตัวแทนจำหน่าย)', '13');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('405', 'ปิโตรเคมีและเคมีภัณฑ์ (ผู้ผลิตและตัวแทนจำหนาย)', '14');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('501', 'วัสดุก่อสร้าง', '15');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('502', 'พัฒนาอสังหาริมทรัพย์', '16');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('601', 'พลังงานและสาธารณูปโภค', '17');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('701', 'พาณิชย์', '18');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('702', 'การแพทย์', '19');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('703', 'สื่อและสิ่งพิมพ์', '20');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('704', 'การท่องเที่ยวและสันทนาการ', '21');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('705', 'ขนส่งและโลจิสติกส์', '22');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('706', 'ไปรษณีย์', '23');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('707', 'กฎหมาย', '24');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('708', 'สถานที่ออกกำลังกาย/ฟิตเนต', '25');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('709', 'ร้านอินเตอร์เน็ต/ร้านเกมส์ออนไลน์', '26');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('710', 'ที่ปรึกษา', '27');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('711', 'บ.รักษาความปลอดภัย', '28');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('801', 'ชิ้นส่วนอิเลคทรอนิกส์', '29');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('802', 'เทคโนโลยีสารสนเทศและการสื่อสาร', '30');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('901', 'สถานฑูตและกงศุล', '31');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('902', 'องค์กรระหว่างประเทศ', '32');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1001', 'สถาบันอุดมศึกษา (มหาวิทยาลัย)', '33');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1002', 'สถาบันอาชีวศึกษา', '34');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1003', 'หน่วยงานจัดการศึกษาต่างประเทศ', '35');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1004', 'โรงเรียนหรือสถาบัน', '36');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1101', 'ข้าราชการ', '37');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1102', 'พนักงานรัฐวิสาหกิจ', '38');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1103', 'พนักงานบริษัทเอกชน', '39');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1104', 'ธุรกิจส่วนตัว', '40');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1106', 'พ่อบ้าน/แม่บ้าน', '41');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1107', 'รับจ้างทั่วไป', '42');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1108', 'เกษียณ', '43');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1109', 'ว่างงาน', '44');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1110', 'พนักงาน กสท', '45');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1111', 'ชาวต่างชาติ', '46');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1201', 'หน่วยงานกำกับ', '47');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1202', 'องค์กรอิสระที่มีสังกัด', '48');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1203', 'กองทุน', '49');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1301', 'สนง.ตำรวจ', '50');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1302', 'หน่วยทหาร', '51');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1501', 'โทรศัพท์ประจำที่', '52');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1502', 'โทรศัพท์สาธารณะ', '53');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1105', 'นักศึกษา', '54');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1503', 'บริการอินเตอร์เน็ต', '55');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1112', 'มัคคุเทศก์', '56');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('1113', 'เกษตรกร', '57');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('712', 'จัดหาแรงงาน', '58');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_TYPE VALUES('713', 'จัดงานกิจกรรม ส่งเสริมการตลาดแบบครบวงจร', '59');
-- DATA FOR CATCRM_CUSTOMER_GROUP
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('1', 'กลุ่มเกษตรและแปรรูป', '1');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('2', 'สินค้าอุปโภคบริโภค', '2');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('3', 'กลุ่มธุรกิจการเงิน (ธนาคาร  บ.เงินทุน  บ.หลักทรัพย์, บ.ประกันภัย ฯลฯ)', '3');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('4', 'กลุ่มสินค้าอุตสาหกรรม', '4');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('5', 'กลุ่มอสังหาริมทรัพย์และก่อสร้าง', '5');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('6', 'กลุ่มทรัพยากร', '6');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('7', 'กลุ่มบริการ', '7');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('8', 'กลุ่มเทคโนโลยี', '8');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('9', 'หน่วยงานระหว่างประเทศ', '9');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('10', 'การศึกษา', '10');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('11', 'ครัวเรือน', '11');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('12', 'กลุ่มราชการ (ไม่รวมรัฐวิสาหกิจ)', '12');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('13', 'หน่วยงานพิเศษ', '13');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('14', 'นำเข้า-ส่งออก', '14');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('15', 'USO', '15');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('16', 'อื่นๆ ได้แก่ องค์กร,มูลนิธิ,สถาบันที่ไม่มีสังกัด,รัฐวิสาหกิจที่ไม่สามารถจัดกลุ่มได้', '16');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('17', 'หน่วยงานภายใน', '17');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_GROUP VALUES('18', 'หน่วยงานภายนอก', '18');
-- DATA FOR CATCRM_CUSTOMER_FOCUS 
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('0', 'อื่น ๆ', '1');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('10101', 'ธุรกิจที่ทำการเพาะปลูก', '2');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('10102', 'ธุรกิจประมง', '3');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('10103', 'ธุรกิจป่าไม้', '4');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('10104', 'ธุรกิจชำแหละและเก็บรักษาสินค้าเกษตร', '5');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('10105', 'ตัวกลางจำหน่ายสินค้าเกษตรให้กับอุตสาหกรรมอื่น', '6');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('10201', 'ธุรกิจแปรรูปอาหารจากผลิตผลทางการเกษตร', '7');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('10202', 'ธุรกิจร้านอาหาร', '8');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('10203', 'ตัวแทนจำหน่ายอาหาร', '9');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('10204', 'ผู้ผลิตเครื่องดื่มทุกชนิด', '10');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('20101', 'เครื่องนุ่งห่ม  รองเท้า  เครื่องหนัง  กระเป๋า', '11');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('20102', 'ผู้เจียรนัยและแปรรูปอัญมนีและเครื่องประดับ', '12');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('20103', 'ผู้ผลิตวัตถุดิบสำหรับอุตสาหกรรม เส้นใย เส้นใหม  ฟอกหนัง  ฯลฯ', '13');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('20201', 'เครื่องใช้ไฟฟ้าภายในบ้าน และสำนักงาน  โทรทัศน์  เครื่องเสียง  เครื่องถ่ายเอกสาร ฯลฯ', '14');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('20202', 'ของใช้สำนักงาน เครื่องเขียน แผ่น CD แฟ้มเอกสาร ปากกา ฯลฯ', '15');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('20301', 'สินค้าอุปโภคส่วนตัวต่างๆ  เครื่องสำอาง ผลิตภัณฑ์บำรุงผิวพรรณ น้ำหอม ผ้าอ้อม กระดาษชำระ', '16');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('20302', 'เครื่องมือทางการแพทย์ ยา อาหารเสริม สินค้าที่ใช้ Biotechnology ต่างๆ', '17');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('30101', 'ผู้ประกอบธุรกิจธนาคารตาม  พรบ. การธนาคารพาณิชย์และกฏหมายที่เกียวข้อง (ธนาคารของรัฐ,เอกชน)', '18');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('30201', 'เช่าซื้อ แฟกเตอริ่ง บัตรเครดิต บ.หลักทรัพย์ จัดการกองทุนรวม', '19');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('30301', 'ผู้ประกอบธุรกิจตาม พรบ. ประกันภัย  พรบ. ประกันชีวิต', '20');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40101', 'ผู้ผลิต  ประกอบรถยนต์และยานยนต์ประเภทต่างๆ', '21');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40102', 'ผู้ผลิต ตัวแทนจำหน่าย ชิ้นส่วนหรืออะไหล่', '22');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40103', 'ซ่อมบำรุง ติดตั้งแก๊ส ตรวจสภาพ', '23');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40104', 'ผู้จัดจำหน่ายและศูนย์จำหน่าย', '24');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40201', 'ผู้ผลิตและจำหน่ายเครื่องจักรและเครื่องมือทุกชนิด', '25');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40202', 'อุปกรณ์หรือส่วนประกอบพื้นฐานของเครื่องใช้ไฟฟ้า  สายไฟ หลอดไฟ ฉนวนไฟฟ้า มอเตอร์ต่างๆ', '26');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40203', 'วัตถุดิบที่ใช้ได้ในหลายอุดสาหกรรม', '27');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40301', 'ผู้ผลิตและตัวแทนจำหน่ายบรรจุภัณฑ์และส่วนประกอบของบรรจุภัณฑ์', '28');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40401', 'เยื่อกระดาษ  กระดาษ  และผลิตภัณฑ์กระดาษทุกชนิด', '29');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40402', 'หมึกสำหรับใช้ในการพิมพ์ต่างๆ', '30');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40501', 'สินค้าในอุตสาหกรรมปิโตเคมี  เม็ดและผงพลาสติก และผลิตภัณฑ์พลาสติกต่างๆ', '31');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('40502', 'สารเคมี  เคมีภัณฑ์พื้นฐาน เคมีภัณฑ์แปรรูปต่างๆ  ปุ๋ย  ยาปราบศัตรูพืช', '32');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('50101', 'ผลิตและจำหน่ายวัสดุก่อสร้าง  วัสดุตกแต่ง  สุขภัณฑ์', '33');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('50201', 'ธุรกิจรับก่อสร้างอาคาร  ที่อยู่อาศัย  สิ่งปลูกสร้างอื่น', '34');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('50202', 'ธุรกิจพัฒนา  บริหาร จัดการ อสังหาริมทรัพย์', '35');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('50203', 'ตัวแทนหรือนายหน้าในการจำหน่ายและให้เช่าอสังหาริมทรัพย์', '36');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('50204', 'กองทุนรวมอสังหาริมทรัพย์', '37');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('60101', 'ผลิต สำรวจ ขุดเจาะ กลั่น และตัวแทนจำหน่ายพลังงานธรรมชาติ เช่นน้ำมันและก๊าซธรรมชาติ', '38');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('60102', 'บริการสาธารณูปโภค ไฟฟ้า ประปา  แก๊ส', '39');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70101', 'จำหน่ายสินค้า ปลีก/ส่ง ให้กับผู้บริโภค ห้างสรรพสินค้า ดิสเคาท์สโตร์ ร้านสะดวกซื้อ e-commerce', '40');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70201', 'ให้บริการทางการแพทย์ โรงพยาบาล คลินิก', '41');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70301', 'ธุรกิจบันเทิง  ดนตรี ภาพยนต์ ฯลฯ', '42');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70302', 'กระจายภาพและเสียง', '43');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70303', 'ผลิตและจัดทำสื่อโฆษณา', '44');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70304', 'ผลิตและจำหน่ายสื่อสิ่งพิมพ์ โรงพิมพ์ สำนักพิมพ์  ฯลฯ', '45');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70401', 'ผู้ประกอบการโรงแรม  ที่พักชั่วคราว  บริษัทนำเที่ยว', '46');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70402', 'สถานที่พักผ่อน,ทัศนศึกษา,สถานบันเทิง,สนามกีฬา,สวนสาธารณะ,พิพิธภัณฑ์,สวนสัตว์ สปา', '47');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70501', 'บริการเกี่ยวกับการขนส่ง และการรับส่งสินค้าแบบครบวงจร ทั้ง ทางอากาศ,ทางน้ำ,ทางบก', '48');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70502', 'Shipping , คลังสินค้า', '49');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70701', 'บ.สำนักทนายความ บัญชี', '50');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('80101', 'ผลิต IC, PCB, Semiconductor', '51');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('80201', 'ผู้ให้บริการโทรคมนาคม', '52');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('80202', 'ผู้ให้บริการเครือข่ายโทรคมนาคม  ดาวเทียม เคเบิ้ล', '53');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('80203', 'ผู้ให้บริการเครือข่าย Internet', '54');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('80204', 'ผู้ให้บริการติดตั้งระบบ (SI)', '55');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('80205', 'ผู้ผลิต/จำหน่าย/ซ่อม อุปกรณ์โทรคมนาคม', '56');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('80206', 'ผู้ผลิต/จำหน่าย/ซ่อม  อุปกรณ์  Computer', '57');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('100401', 'มัธยมหรือต่ำกว่า', '58');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('100402', 'กวดวิชา', '59');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('100403', 'สถาบันสอนภาษาและคอมพิวเตอร์', '60');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('150101', 'หมู่บ้าน CDMA', '61');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('150102', 'หมู่บ้าน VSAT', '62');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('150103', 'อนามัย CDMA', '63');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('150104', 'อนามัย VSAT', '64');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('150105', 'อนามัย IPSTAR', '65');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('150106', 'ชุมชนรายได้น้อย CDMA', '66');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('150107', 'คนพิการ CDMA', '67');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('150108', 'โรงเรียนตำรวจตระเวนชายแดน CDMA', '68');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('150109', 'เชิงพาณิชย์', '69');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('10106', 'ธุรกิจปศุสัตว์', '70');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('20203', 'เฟอร์นิเจอร์ เครื่องครัว ฯลฯ', '71');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('60103', 'การทำเหมืองแร่ เหมืองหิน', '72');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('70702', 'ตัวแทน นายหน้า ค้ำประกัน', '73');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('71200', 'อื่นๆ', '74');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('71301', 'จัดงาน Event ต่างๆ (Organize)', '75');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110101', 'ครู', '76');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110102', 'ทหาร', '77');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110103', 'ตำรวจ', '78');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110104', 'นักกฏหมาย', '79');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110105', 'แพทย์ พยาบาล เภสัชกร', '80');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110301', 'ทนายความ', '81');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110302', 'แพทย์ พยาบาล เภสัชกร', '82');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110303', 'นักบัญขี การเงิน', '83');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110304', 'พนักงานขาย', '84');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110305', 'วิศวกร สถาปนิก', '85');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110306', 'โปรแกรมเมอร์', '86');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110307', 'ช่างเทคนิค', '87');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110308', 'ตัวแทนขายประกัน', '88');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110401', 'ค้าขาย', '89');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110402', 'ช่างเสริมสวย', '90');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110403', 'ช่างภาพ', '91');
INSERT INTO CRMDATA.CATCRM_CUSTOMER_FOCUS VALUES('110404', 'อาชีพอิสระ', '92');