
package th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.f02_retrieveinvoiceaccountcodesi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:17:12.427+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class F02RetrieveInvoiceAccountCodeSI_F02RetrieveInvoiceAccountCodeSIExport1F02RetrieveInvoiceAccountCodeSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://F02_RetrieveInvoiceAccountCode/F02_RetrieveInvoiceAccountCodeSI", "F02_RetrieveInvoiceAccountCodeSIExport1_F02_RetrieveInvoiceAccountCodeSIHttpService");

    private F02RetrieveInvoiceAccountCodeSI_F02RetrieveInvoiceAccountCodeSIExport1F02RetrieveInvoiceAccountCodeSIHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = F02RetrieveInvoiceAccountCodeSIExport1F02RetrieveInvoiceAccountCodeSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        F02RetrieveInvoiceAccountCodeSIExport1F02RetrieveInvoiceAccountCodeSIHttpService ss = new F02RetrieveInvoiceAccountCodeSIExport1F02RetrieveInvoiceAccountCodeSIHttpService(wsdlURL, SERVICE_NAME);
        F02RetrieveInvoiceAccountCodeSI port = ss.getF02RetrieveInvoiceAccountCodeSIExport1F02RetrieveInvoiceAccountCodeSIHttpPort();  
        
        {
        System.out.println("Invoking retrieveInvoiceAccountCodeInfo...");
            th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.RetrieveInvoiceAccountCodeRequest _retrieveInvoiceAccountCodeInfo_retrieveInvoiceAccountCodeRequest = null;
            th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.RetrieveInvoiceAccountCodeResponse _retrieveInvoiceAccountCodeInfo__return = port.retrieveInvoiceAccountCodeInfo(_retrieveInvoiceAccountCodeInfo_retrieveInvoiceAccountCodeRequest);
        System.out.println("retrieveInvoiceAccountCodeInfo.result=" + _retrieveInvoiceAccountCodeInfo__return);


        }

        System.exit(0);
    }

}
