
package th.net.cat.epis.ws.m03_createreceipt.m03_createreceiptsi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:28:56.413+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class M03CreateReceiptSI_M03CreateReceiptSIExport1M03CreateReceiptSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://M03_CreateReceipt/M03_CreateReceiptSI", "M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpService");

    private M03CreateReceiptSI_M03CreateReceiptSIExport1M03CreateReceiptSIHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = M03CreateReceiptSIExport1M03CreateReceiptSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        M03CreateReceiptSIExport1M03CreateReceiptSIHttpService ss = new M03CreateReceiptSIExport1M03CreateReceiptSIHttpService(wsdlURL, SERVICE_NAME);
        M03CreateReceiptSI port = ss.getM03CreateReceiptSIExport1M03CreateReceiptSIHttpPort();  
        
        {
        System.out.println("Invoking createReceiptInfo...");
            th.net.cat.epis.ws.m03_createreceipt.CreateReceiptRequest _createReceiptInfo_createReceiptRequest = null;
            th.net.cat.epis.ws.m03_createreceipt.CreateReceiptResponse _createReceiptInfo__return = port.createReceiptInfo(_createReceiptInfo_createReceiptRequest);
        System.out.println("createReceiptInfo.result=" + _createReceiptInfo__return);


        }

        System.exit(0);
    }

}
