
package th.net.cat.epis.ws.f05_retrieveservicestatus.f05_retrieveservicestatussi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:17:45.157+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class F05RetrieveServiceStatusSI_F05RetrieveServiceStatusSIExport1F05RetrieveServiceStatusSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://F05_RetrieveServiceStatus/F05_RetrieveServiceStatusSI", "F05_RetrieveServiceStatusSIExport1_F05_RetrieveServiceStatusSIHttpService");

    private F05RetrieveServiceStatusSI_F05RetrieveServiceStatusSIExport1F05RetrieveServiceStatusSIHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = F05RetrieveServiceStatusSIExport1F05RetrieveServiceStatusSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        F05RetrieveServiceStatusSIExport1F05RetrieveServiceStatusSIHttpService ss = new F05RetrieveServiceStatusSIExport1F05RetrieveServiceStatusSIHttpService(wsdlURL, SERVICE_NAME);
        F05RetrieveServiceStatusSI port = ss.getF05RetrieveServiceStatusSIExport1F05RetrieveServiceStatusSIHttpPort();  
        
        {
        System.out.println("Invoking checkServiceStatus...");
            th.net.cat.epis.ws.f05_retrieveservicestatus.RetrieveServiceStatusRequest _checkServiceStatus_retrieveServiceStatusRequest = null;
            th.net.cat.epis.ws.f05_retrieveservicestatus.RetrieveServiceStatusResponse _checkServiceStatus__return = port.checkServiceStatus(_checkServiceStatus_retrieveServiceStatusRequest);
        System.out.println("checkServiceStatus.result=" + _checkServiceStatus__return);


        }

        System.exit(0);
    }

}
