<%-- 
    Document   : test
    Created on : Dec 16, 2015, 1:16:24 AM
    Author     : AmMie
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <link href="../scripts/bootstrap-table-1.8.1/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="../scripts/bootstrap-table-1.8.1/bootstrap-table/src/bootstrap-table.css" rel="stylesheet" type="text/css"/>

        <script src="../scripts/bootstrap-table-1.8.1/jquery.min.js" type="text/javascript"></script>
        <script src="../scripts/bootstrap-table-1.8.1/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="../scripts/bootstrap-table-1.8.1/bootstrap-table/src/bootstrap-table.js"></script>

    </head>
    <style>



    </style>
    <body class="menu">
        <div class="container">
            <div>
                <h1>Example - expand row</h1>
            </div>
            <div id="toolbar">
            </div>
            <table  id="myTable"
                    data-toggle="table"
                    data-detail-view="true"
                    data-detail-formatter="detailFormatter">
                <thead>
                    <tr>
                        <th>Column A</th>
                        <th>Column B</th>
                        <th>Column C</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>abcd</td>
                        <td>other content</td>
                        <!-- id number is generated by tt_template -->
                <span style="display: none;" id="desc0">
                    <strong class="bold">Description:</strong>
                    <br>
                    <pre>This is row with id=0, containing other content</pre>
                </span>
                </tr>
                <tr>
                    <td>2</td>
                    <td>efgh</td>
                    <td>another content</td>
                    <!-- id number is generated by tt_template -->
                <span style="display: none;" id="desc1">
                    <strong class="bold">Description:</strong>
                    <br>
                    <pre>This is row with id=1, containing another content</pre>
                </span>
                </tr>
                </tbody>
            </table>
        </div>
    </body>
    <script>
        /* Latest compiled and minified JavaScript included as External Resource */

        var $table = $('#myTable');

        $table.on('expand-row.bs.table', function (e, index, row, $detail) {
            var res = $("#desc" + index).html();
            $detail.html(res);
        });

        $table.on("click-row.bs.table", function (e, row, $tr) {

            // prints Clicked on: table table-hover, no matter if you click on row or detail-icon
            console.log("Clicked on: " + $(e.target).attr('class'));

            // In my real scenarion, trigger expands row with text detailFormatter..
            //$tr.find(">td>.detail-icon").trigger("click");
            $tr.find(">td>.detail-icon").triggerHandler("click");
        });



    </script>
</html>
