
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.m02_findorderdetail.m02_findorderdetailsi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-26T01:32:30.558+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "M02_FindOrderDetailSIExport1_M02_FindOrderDetailSIHttpService",
                      portName = "M02_FindOrderDetailSIExport1_M02_FindOrderDetailSIHttpPort",
                      targetNamespace = "http://M02_FindOrderDetail/M02_FindOrderDetailSI",
                     // wsdlLocation = "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M02_FindOrderDetail_M02_FindOrderDetailSIExport1.wsdl",
                      endpointInterface = "th.net.cat.epis.ws.m02_findorderdetail.m02_findorderdetailsi.M02FindOrderDetailSI")
                      
public class M02_FindOrderDetailSIExport1_M02_FindOrderDetailSIHttpPortImpl implements M02FindOrderDetailSI {

    private static final Logger LOG = Logger.getLogger(M02_FindOrderDetailSIExport1_M02_FindOrderDetailSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see th.net.cat.epis.ws.m02_findorderdetail.m02_findorderdetailsi.M02FindOrderDetailSI#findOrderDetailInfo(m02_findorderdetail.FindOrderDetailRequest  findOrderDetailRequest )*
     */
    public th.net.cat.epis.ws.m02_findorderdetail.FindOrderDetailResponse findOrderDetailInfo(th.net.cat.epis.ws.m02_findorderdetail.FindOrderDetailRequest findOrderDetailRequest) {
        LOG.info("Executing operation findOrderDetailInfo");
        System.out.println(findOrderDetailRequest);
        try {
            th.net.cat.epis.ws.m02_findorderdetail.FindOrderDetailResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
