
package th.net.cat.epis.ws.m02_findorderdetail.m02_findorderdetailsi;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-26T01:32:30.576+07:00
 * Generated source version: 3.1.6
 * 
 */
 
public class M02FindOrderDetailSI_M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpPort_Server{

    protected M02FindOrderDetailSI_M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new M02_FindOrderDetailSIExport1_M02_FindOrderDetailSIHttpPortImpl();
        String address = "http://10.32.23.134:7800/M02_FindOrderDetailSIExport1_M02_FindOrderDetailSIHttpService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new M02FindOrderDetailSI_M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
