
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.f19_retrieveaccount.f19_retrieveaccountsi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:19:49.050+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpService",
                      portName = "F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpPort",
                      targetNamespace = "http://F19_RetrieveAccount/F19_RetrieveAccountSI",
                      wsdlLocation = "http://10.32.23.134:7800/F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpService?wsdl",
                      endpointInterface = "th.net.cat.epis.ws.f19_retrieveaccount.f19_retrieveaccountsi.F19RetrieveAccountSI")
                      
public class F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpPortImpl implements F19RetrieveAccountSI {

    private static final Logger LOG = Logger.getLogger(F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see f19_retrieveaccount.f19_retrieveaccountsi.F19RetrieveAccountSI#retrieveAccountInfo(f19_retrieveaccount.RetrieveAccountRequest  retrieveAccountRequest )*
     */
    public th.net.cat.epis.ws.f19_retrieveaccount.RetrieveAccountResponse retrieveAccountInfo(th.net.cat.epis.ws.f19_retrieveaccount.RetrieveAccountRequest retrieveAccountRequest) {
        LOG.info("Executing operation retrieveAccountInfo");
        System.out.println(retrieveAccountRequest);
        try {
            th.net.cat.epis.ws.f19_retrieveaccount.RetrieveAccountResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
