package th.net.cat.epis.ws.f19_retrieveaccount.f19_retrieveaccountsi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:19:49.073+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpService", 
                  wsdlLocation = "http://10.32.23.134:7800/F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpService?wsdl",
                  targetNamespace = "http://F19_RetrieveAccount/F19_RetrieveAccountSI") 
public class F19RetrieveAccountSIExport1F19RetrieveAccountSIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://F19_RetrieveAccount/F19_RetrieveAccountSI", "F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpService");
    public final static QName F19RetrieveAccountSIExport1F19RetrieveAccountSIHttpPort = new QName("http://F19_RetrieveAccount/F19_RetrieveAccountSI", "F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.32.23.134:7800/F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(F19RetrieveAccountSIExport1F19RetrieveAccountSIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.32.23.134:7800/F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public F19RetrieveAccountSIExport1F19RetrieveAccountSIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public F19RetrieveAccountSIExport1F19RetrieveAccountSIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public F19RetrieveAccountSIExport1F19RetrieveAccountSIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public F19RetrieveAccountSIExport1F19RetrieveAccountSIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public F19RetrieveAccountSIExport1F19RetrieveAccountSIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public F19RetrieveAccountSIExport1F19RetrieveAccountSIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns F19RetrieveAccountSI
     */
    @WebEndpoint(name = "F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpPort")
    public F19RetrieveAccountSI getF19RetrieveAccountSIExport1F19RetrieveAccountSIHttpPort() {
        return super.getPort(F19RetrieveAccountSIExport1F19RetrieveAccountSIHttpPort, F19RetrieveAccountSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns F19RetrieveAccountSI
     */
    @WebEndpoint(name = "F19_RetrieveAccountSIExport1_F19_RetrieveAccountSIHttpPort")
    public F19RetrieveAccountSI getF19RetrieveAccountSIExport1F19RetrieveAccountSIHttpPort(WebServiceFeature... features) {
        return super.getPort(F19RetrieveAccountSIExport1F19RetrieveAccountSIHttpPort, F19RetrieveAccountSI.class, features);
    }

}
