
package th.co.softpos.ws.mg.s004;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-08-03T15:13:47.666+07:00
 * Generated source version: 3.1.6
 * 
 */
 
public class S004MGUpdFree_S004MGUpdFreePort_Server{

    protected S004MGUpdFree_S004MGUpdFreePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new S004MGUpdFreePortImpl();
        String address = "http://10.44.1.4/InsalePosWS/services/S004MGUpdFree";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new S004MGUpdFree_S004MGUpdFreePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
