
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.f08_writeoffinquirypos.f08_writeoffinquirysi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:18:10.985+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "F08_WriteOffInquirySIExport1_F08_WriteOffInquirySIHttpService",
                      portName = "F08_WriteOffInquirySIExport1_F08_WriteOffInquirySIHttpPort",
                      targetNamespace = "http://F08_WriteOffInquiryPOS/F08_WriteOffInquirySI",
                      wsdlLocation = "http://10.32.23.134:7800/F08_WriteOffInquirySIExport1_F08_WriteOffInquirySIHttpService?wsdl",
                      endpointInterface = "th.net.cat.epis.ws.f08_writeoffinquirypos.f08_writeoffinquirysi.F08WriteOffInquirySI")
                      
public class F08_WriteOffInquirySIExport1_F08_WriteOffInquirySIHttpPortImpl implements F08WriteOffInquirySI {

    private static final Logger LOG = Logger.getLogger(F08_WriteOffInquirySIExport1_F08_WriteOffInquirySIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see f08_writeoffinquirypos.f08_writeoffinquirysi.F08WriteOffInquirySI#retrieveWriteOffInvoice(f08_writeoffinquirypos.RetrieveWriteOffInvoiceRequest  retrieveWriteOffInvoiceRequest )*
     */
    public th.net.cat.epis.ws.f08_writeoffinquirypos.RetrieveWriteOffInvoiceResponse retrieveWriteOffInvoice(th.net.cat.epis.ws.f08_writeoffinquirypos.RetrieveWriteOffInvoiceRequest retrieveWriteOffInvoiceRequest) {
        LOG.info("Executing operation retrieveWriteOffInvoice");
        System.out.println(retrieveWriteOffInvoiceRequest);
        try {
            th.net.cat.epis.ws.f08_writeoffinquirypos.RetrieveWriteOffInvoiceResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
