
package th.net.cat.epis.service.adapter.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2559-04-20T22:43:36.288+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class GeoIPServiceHttpPost_GeoIPServiceHttpPost_Client {

    private static final QName SERVICE_NAME = new QName("http://www.webservicex.net/", "GeoIPService");

    private GeoIPServiceHttpPost_GeoIPServiceHttpPost_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GeoIPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GeoIPService ss = new GeoIPService(wsdlURL, SERVICE_NAME);
        GeoIPServiceHttpPost port = ss.getGeoIPServiceHttpPost();  
        
        {
        System.out.println("Invoking getGeoIP...");
        java.lang.String _getGeoIP_ipAddress = "";
        GeoIP _getGeoIP__return = port.getGeoIP(_getGeoIP_ipAddress);
        System.out.println("getGeoIP.result=" + _getGeoIP__return);


        }
        {
        System.out.println("Invoking getGeoIPContext...");
        GeoIP _getGeoIPContext__return = port.getGeoIPContext();
        System.out.println("getGeoIPContext.result=" + _getGeoIPContext__return);


        }

        System.exit(0);
    }

}
