package th.net.cat.epis.ws.f06_reversepayment.f06_reversepaymentsi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:17:54.345+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpService", 
                  wsdlLocation = "http://10.32.23.134:7800/F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpService?wsdl",
                  targetNamespace = "http://F06_ReversePayment/F06_ReversePaymentSI") 
public class F06ReversePaymentSIExport1F06ReversePaymentSIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://F06_ReversePayment/F06_ReversePaymentSI", "F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpService");
    public final static QName F06ReversePaymentSIExport1F06ReversePaymentSIHttpPort = new QName("http://F06_ReversePayment/F06_ReversePaymentSI", "F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.32.23.134:7800/F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(F06ReversePaymentSIExport1F06ReversePaymentSIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.32.23.134:7800/F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public F06ReversePaymentSIExport1F06ReversePaymentSIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public F06ReversePaymentSIExport1F06ReversePaymentSIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public F06ReversePaymentSIExport1F06ReversePaymentSIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public F06ReversePaymentSIExport1F06ReversePaymentSIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public F06ReversePaymentSIExport1F06ReversePaymentSIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public F06ReversePaymentSIExport1F06ReversePaymentSIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns F06ReversePaymentSI
     */
    @WebEndpoint(name = "F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpPort")
    public F06ReversePaymentSI getF06ReversePaymentSIExport1F06ReversePaymentSIHttpPort() {
        return super.getPort(F06ReversePaymentSIExport1F06ReversePaymentSIHttpPort, F06ReversePaymentSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns F06ReversePaymentSI
     */
    @WebEndpoint(name = "F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpPort")
    public F06ReversePaymentSI getF06ReversePaymentSIExport1F06ReversePaymentSIHttpPort(WebServiceFeature... features) {
        return super.getPort(F06ReversePaymentSIExport1F06ReversePaymentSIHttpPort, F06ReversePaymentSI.class, features);
    }

}
