package th.net.cat.epis.ws.m02_findorderdetail.m02_findorderdetailsi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-26T01:32:30.581+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "M02_FindOrderDetailSIExport1_M02_FindOrderDetailSIHttpService", 
                 // wsdlLocation = "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M02_FindOrderDetail_M02_FindOrderDetailSIExport1.wsdl",
                  targetNamespace = "http://M02_FindOrderDetail/M02_FindOrderDetailSI") 
public class M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://M02_FindOrderDetail/M02_FindOrderDetailSI", "M02_FindOrderDetailSIExport1_M02_FindOrderDetailSIHttpService");
    public final static QName M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpPort = new QName("http://M02_FindOrderDetail/M02_FindOrderDetailSI", "M02_FindOrderDetailSIExport1_M02_FindOrderDetailSIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M02_FindOrderDetail_M02_FindOrderDetailSIExport1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M02_FindOrderDetail_M02_FindOrderDetailSIExport1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns M02FindOrderDetailSI
     */
    @WebEndpoint(name = "M02_FindOrderDetailSIExport1_M02_FindOrderDetailSIHttpPort")
    public M02FindOrderDetailSI getM02FindOrderDetailSIExport1M02FindOrderDetailSIHttpPort() {
        return super.getPort(M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpPort, M02FindOrderDetailSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns M02FindOrderDetailSI
     */
    @WebEndpoint(name = "M02_FindOrderDetailSIExport1_M02_FindOrderDetailSIHttpPort")
    public M02FindOrderDetailSI getM02FindOrderDetailSIExport1M02FindOrderDetailSIHttpPort(WebServiceFeature... features) {
        return super.getPort(M02FindOrderDetailSIExport1M02FindOrderDetailSIHttpPort, M02FindOrderDetailSI.class, features);
    }

}
