package th.net.cat.epis.ws.m02_findorderdetail.m02_findorderdetailsi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-26T01:32:30.569+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://M02_FindOrderDetail/M02_FindOrderDetailSI", name = "M02_FindOrderDetailSI")
@XmlSeeAlso({th.net.cat.epis.ws.m02_findorderdetail.ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class, ObjectFactory.class})
public interface M02FindOrderDetailSI {

    @WebResult(name = "findOrderDetailResponse", targetNamespace = "")
    @RequestWrapper(localName = "findOrderDetailInfo", targetNamespace = "http://M02_FindOrderDetail/M02_FindOrderDetailSI", className = "th.net.cat.epis.ws.m02_findorderdetail.m02_findorderdetailsi.FindOrderDetailInfo")
    @WebMethod
    @ResponseWrapper(localName = "findOrderDetailInfoResponse", targetNamespace = "http://M02_FindOrderDetail/M02_FindOrderDetailSI", className = "th.net.cat.epis.ws.m02_findorderdetail.m02_findorderdetailsi.FindOrderDetailInfoResponse")
    public th.net.cat.epis.ws.m02_findorderdetail.FindOrderDetailResponse findOrderDetailInfo(
            @WebParam(name = "findOrderDetailRequest", targetNamespace = "")
                    th.net.cat.epis.ws.m02_findorderdetail.FindOrderDetailRequest findOrderDetailRequest
    );
}
