
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.f11_reversewriteoffpos.f11_reversewriteoffsi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:18:48.178+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpService",
                      portName = "F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpPort",
                      targetNamespace = "http://F11_ReverseWriteOffPOS/F11_ReverseWriteOffSI",
                      wsdlLocation = "http://10.32.23.134:7800/F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpService?wsdl",
                      endpointInterface = "th.net.cat.epis.ws.f11_reversewriteoffpos.f11_reversewriteoffsi.F11ReverseWriteOffSI")
                      
public class F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpPortImpl implements F11ReverseWriteOffSI {

    private static final Logger LOG = Logger.getLogger(F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see f11_reversewriteoffpos.f11_reversewriteoffsi.F11ReverseWriteOffSI#reverseWriteOff(f11_reversewriteoffpos.ReverseWriteOffRequest  reverseWriteOffRequest )*
     */
    public th.net.cat.epis.ws.f11_reversewriteoffpos.ReverseWriteOffResponse reverseWriteOff(th.net.cat.epis.ws.f11_reversewriteoffpos.ReverseWriteOffRequest reverseWriteOffRequest) {
        LOG.info("Executing operation reverseWriteOff");
        System.out.println(reverseWriteOffRequest);
        try {
            th.net.cat.epis.ws.f11_reversewriteoffpos.ReverseWriteOffResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
