
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.m03_createreceipt.m03_createreceiptsi;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:28:56.434+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpService",
                      portName = "M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpPort",
                      targetNamespace = "http://M03_CreateReceipt/M03_CreateReceiptSI",
                     // wsdlLocation = "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M03_CreateReceipt_M03_CreateReceiptSIExport1.wsdl",
                      endpointInterface = "th.net.cat.epis.ws.m03_createreceipt.m03_createreceiptsi.M03CreateReceiptSI")
                      
public class M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpPortImpl implements M03CreateReceiptSI {

    private static final Logger LOG = Logger.getLogger(M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see m03_createreceipt.m03_createreceiptsi.M03CreateReceiptSI#createReceiptInfo(m03_createreceipt.CreateReceiptRequest  createReceiptRequest )*
     */
    public th.net.cat.epis.ws.m03_createreceipt.CreateReceiptResponse createReceiptInfo(th.net.cat.epis.ws.m03_createreceipt.CreateReceiptRequest createReceiptRequest) {
        LOG.info("Executing operation createReceiptInfo");
        System.out.println(createReceiptRequest);
        try {
            th.net.cat.epis.ws.m03_createreceipt.CreateReceiptResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
