package th.net.cat.epis.ws.m03_createreceipt.m03_createreceiptsi;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:28:56.458+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpService", 
                 // wsdlLocation = "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M03_CreateReceipt_M03_CreateReceiptSIExport1.wsdl",
                  targetNamespace = "http://M03_CreateReceipt/M03_CreateReceiptSI") 
public class M03CreateReceiptSIExport1M03CreateReceiptSIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://M03_CreateReceipt/M03_CreateReceiptSI", "M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpService");
    public final static QName M03CreateReceiptSIExport1M03CreateReceiptSIHttpPort = new QName("http://M03_CreateReceipt/M03_CreateReceiptSI", "M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M03_CreateReceipt_M03_CreateReceiptSIExport1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(M03CreateReceiptSIExport1M03CreateReceiptSIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M03_CreateReceipt_M03_CreateReceiptSIExport1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public M03CreateReceiptSIExport1M03CreateReceiptSIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public M03CreateReceiptSIExport1M03CreateReceiptSIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public M03CreateReceiptSIExport1M03CreateReceiptSIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public M03CreateReceiptSIExport1M03CreateReceiptSIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public M03CreateReceiptSIExport1M03CreateReceiptSIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public M03CreateReceiptSIExport1M03CreateReceiptSIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns M03CreateReceiptSI
     */
    @WebEndpoint(name = "M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpPort")
    public M03CreateReceiptSI getM03CreateReceiptSIExport1M03CreateReceiptSIHttpPort() {
        return super.getPort(M03CreateReceiptSIExport1M03CreateReceiptSIHttpPort, M03CreateReceiptSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns M03CreateReceiptSI
     */
    @WebEndpoint(name = "M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpPort")
    public M03CreateReceiptSI getM03CreateReceiptSIExport1M03CreateReceiptSIHttpPort(WebServiceFeature... features) {
        return super.getPort(M03CreateReceiptSIExport1M03CreateReceiptSIHttpPort, M03CreateReceiptSI.class, features);
    }

}
