package th.net.cat.epis.ws.f01_retrieveinvoiceheader.f01_retrieveinvoiceheadersi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:16:54.637+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://F01_RetrieveInvoiceHeader/F01_RetrieveInvoiceHeaderSI", name = "F01_RetrieveInvoiceHeaderSI")
@XmlSeeAlso({ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class, th.net.cat.epis.ws.f01_retrieveinvoiceheader.ObjectFactory.class})
public interface F01RetrieveInvoiceHeaderSI {

    @WebResult(name = "retrieveInvoiceHeaderResponse", targetNamespace = "")
    @RequestWrapper(localName = "retrieveInvoiceHeaderInfo", targetNamespace = "http://F01_RetrieveInvoiceHeader/F01_RetrieveInvoiceHeaderSI", className = "th.net.cat.epis.ws.f01_retrieveinvoiceheader.f01_retrieveinvoiceheadersi.RetrieveInvoiceHeaderInfo")
    @WebMethod
    @ResponseWrapper(localName = "retrieveInvoiceHeaderInfoResponse", targetNamespace = "http://F01_RetrieveInvoiceHeader/F01_RetrieveInvoiceHeaderSI", className = "th.net.cat.epis.ws.f01_retrieveinvoiceheader.f01_retrieveinvoiceheadersi.RetrieveInvoiceHeaderInfoResponse")
    public th.net.cat.epis.ws.f01_retrieveinvoiceheader.RetrieveInvoiceHeaderResponse retrieveInvoiceHeaderInfo(
            @WebParam(name = "retrieveInvoiceHeaderRequest", targetNamespace = "")
                    th.net.cat.epis.ws.f01_retrieveinvoiceheader.RetrieveInvoiceHeaderRequest retrieveInvoiceHeaderRequest
    );
}
