
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.f20_retrievesubscrbyinv.f20_retrievesubscrbyinvsi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:19:56.939+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpService",
                      portName = "F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpPort",
                      targetNamespace = "http://F20_RetrieveSubscrByInv/F20_RetrieveSubscrByInvSI",
                      wsdlLocation = "http://10.32.23.134:7800/F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpService?wsdl",
                      endpointInterface = "th.net.cat.epis.ws.f20_retrievesubscrbyinv.f20_retrievesubscrbyinvsi.F20RetrieveSubscrByInvSI")
                      
public class F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpPortImpl implements F20RetrieveSubscrByInvSI {

    private static final Logger LOG = Logger.getLogger(F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see f20_retrievesubscrbyinv.f20_retrievesubscrbyinvsi.F20RetrieveSubscrByInvSI#retrieveSubscr(f20_retrievesubscrbyinv.RetrieveSubscrRequest  retrieveSubscrRequest )*
     */
    public th.net.cat.epis.ws.f20_retrievesubscrbyinv.RetrieveSubscrResponse retrieveSubscr(th.net.cat.epis.ws.f20_retrievesubscrbyinv.RetrieveSubscrRequest retrieveSubscrRequest) {
        LOG.info("Executing operation retrieveSubscr");
        System.out.println(retrieveSubscrRequest);
        try {
            th.net.cat.epis.ws.f20_retrievesubscrbyinv.RetrieveSubscrResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
