
package th.net.cat.epis.ws.f20_retrievesubscrbyinv.f20_retrievesubscrbyinvsi;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-01-10T16:45:27.906+07:00
 * Generated source version: 3.1.6
 * 
 */
 
public class F20RetrieveSubscrByInvSI_F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpPort_Server{

    protected F20RetrieveSubscrByInvSI_F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpPortImpl();
        String address = "http://10.32.23.134:7800/F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new F20RetrieveSubscrByInvSI_F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
