package th.net.cat.epis.ws.f20_retrievesubscrbyinv.f20_retrievesubscrbyinvsi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:19:56.954+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://F20_RetrieveSubscrByInv/F20_RetrieveSubscrByInvSI", name = "F20_RetrieveSubscrByInvSI")
@XmlSeeAlso({ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class, th.net.cat.epis.ws.f20_retrievesubscrbyinv.ObjectFactory.class})
public interface F20RetrieveSubscrByInvSI {

    @WebResult(name = "retrieveSubscrResponse", targetNamespace = "")
    @RequestWrapper(localName = "retrieveSubscr", targetNamespace = "http://F20_RetrieveSubscrByInv/F20_RetrieveSubscrByInvSI", className = "th.net.cat.epis.ws.f20_retrievesubscrbyinv.f20_retrievesubscrbyinvsi.RetrieveSubscr")
    @WebMethod
    @ResponseWrapper(localName = "retrieveSubscrResponse", targetNamespace = "http://F20_RetrieveSubscrByInv/F20_RetrieveSubscrByInvSI", className = "th.net.cat.epis.ws.f20_retrievesubscrbyinv.f20_retrievesubscrbyinvsi.RetrieveSubscrResponse")
    public th.net.cat.epis.ws.f20_retrievesubscrbyinv.RetrieveSubscrResponse retrieveSubscr(
            @WebParam(name = "retrieveSubscrRequest", targetNamespace = "")
                    th.net.cat.epis.ws.f20_retrievesubscrbyinv.RetrieveSubscrRequest retrieveSubscrRequest
    );
}
