
package th.net.cat.epis.ws.f01_retrieveinvoiceheader.f01_retrieveinvoiceheadersi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:16:54.602+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class F01RetrieveInvoiceHeaderSI_F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://F01_RetrieveInvoiceHeader/F01_RetrieveInvoiceHeaderSI", "F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpService");

    private F01RetrieveInvoiceHeaderSI_F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpService ss = new F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpService(wsdlURL, SERVICE_NAME);
        F01RetrieveInvoiceHeaderSI port = ss.getF01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpPort();  
        
        {
        System.out.println("Invoking retrieveInvoiceHeaderInfo...");
            th.net.cat.epis.ws.f01_retrieveinvoiceheader.RetrieveInvoiceHeaderRequest _retrieveInvoiceHeaderInfo_retrieveInvoiceHeaderRequest = null;
            th.net.cat.epis.ws.f01_retrieveinvoiceheader.RetrieveInvoiceHeaderResponse _retrieveInvoiceHeaderInfo__return = port.retrieveInvoiceHeaderInfo(_retrieveInvoiceHeaderInfo_retrieveInvoiceHeaderRequest);
        System.out.println("retrieveInvoiceHeaderInfo.result=" + _retrieveInvoiceHeaderInfo__return);


        }

        System.exit(0);
    }

}
