package th.co.softpos.ws.mg.s001;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-08-02T16:54:33.793+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://s001.mg.ws.softpos.co.th/", name = "S001MGInqGiftvoucher")
@XmlSeeAlso({ObjectFactory.class})
public interface S001MGInqGiftvoucher {

    @WebResult(name = "rs", targetNamespace = "")
    @RequestWrapper(localName = "process", targetNamespace = "http://s001.mg.ws.softpos.co.th/", className = "th.co.softpos.ws.mg.s001.Process")
    @WebMethod
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://s001.mg.ws.softpos.co.th/", className = "th.co.softpos.ws.mg.s001.ProcessResponse")
    public th.co.softpos.ws.mg.s001.Response process(
        @WebParam(name = "rq", targetNamespace = "")
        th.co.softpos.ws.mg.s001.Request rq
    );
}
