package th.co.softpos.ws.mg.s001;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-08-02T16:54:33.810+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "S001MGInqGiftvoucherService", 
                  wsdlLocation = "http://10.44.1.4/InsalePosWS/services/S001MGInqGiftvoucher?wsdl",
                  targetNamespace = "http://s001.mg.ws.softpos.co.th/") 
public class S001MGInqGiftvoucherService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://s001.mg.ws.softpos.co.th/", "S001MGInqGiftvoucherService");
    public final static QName S001MGInqGiftvoucherPort = new QName("http://s001.mg.ws.softpos.co.th/", "S001MGInqGiftvoucherPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.44.1.4/InsalePosWS/services/S001MGInqGiftvoucher?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(S001MGInqGiftvoucherService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.44.1.4/InsalePosWS/services/S001MGInqGiftvoucher?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public S001MGInqGiftvoucherService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public S001MGInqGiftvoucherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public S001MGInqGiftvoucherService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public S001MGInqGiftvoucherService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public S001MGInqGiftvoucherService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public S001MGInqGiftvoucherService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns S001MGInqGiftvoucher
     */
    @WebEndpoint(name = "S001MGInqGiftvoucherPort")
    public S001MGInqGiftvoucher getS001MGInqGiftvoucherPort() {
        return super.getPort(S001MGInqGiftvoucherPort, S001MGInqGiftvoucher.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns S001MGInqGiftvoucher
     */
    @WebEndpoint(name = "S001MGInqGiftvoucherPort")
    public S001MGInqGiftvoucher getS001MGInqGiftvoucherPort(WebServiceFeature... features) {
        return super.getPort(S001MGInqGiftvoucherPort, S001MGInqGiftvoucher.class, features);
    }

}
