
package th.net.cat.epis.ws.esblibs.inf.esb.f4;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import th.net.cat.epis.ws.esblibs.inf.esb.f4.binding.F4CreatePaymentSIExport1F4CreatePaymentSIHttpService;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2559-04-21T09:38:58.227+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class F4CreatePaymentSI_F4CreatePaymentSIExport1F4CreatePaymentSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ESBLibs/INF/ESB/F4/Binding", "F4_CreatePaymentSIExport1_F4_CreatePaymentSIHttpService");

    private F4CreatePaymentSI_F4CreatePaymentSIExport1F4CreatePaymentSIHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = F4CreatePaymentSIExport1F4CreatePaymentSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        F4CreatePaymentSIExport1F4CreatePaymentSIHttpService ss = new F4CreatePaymentSIExport1F4CreatePaymentSIHttpService(wsdlURL, SERVICE_NAME);
        F4CreatePaymentSI port = ss.getF4CreatePaymentSIExport1F4CreatePaymentSIHttpPort();  
        
        {
        System.out.println("Invoking createPayment...");
        th.net.cat.epis.ws.esblibs.requestresponsecbo.f4.CreatePaymentRequest _createPayment_createPaymentRequest = null;
        th.net.cat.epis.ws.esblibs.requestresponsecbo.f4.CreatePaymentResponse _createPayment__return = port.createPayment(_createPayment_createPaymentRequest);
        System.out.println("createPayment.result=" + _createPayment__return);


        }

        System.exit(0);
    }

}
