
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.f09_retrievewriteoffpaymenthistorysi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:18:24.711+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpService",
                      portName = "F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpPort",
                      targetNamespace = "http://F09_WriteOffPaymentHistoryInquiryPOS/F09_RetrieveWriteOffPaymentHistorySI",
                      wsdlLocation = "http://10.32.23.134:7800/F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpService?wsdl",
                      endpointInterface = "th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.f09_retrievewriteoffpaymenthistorysi.F09RetrieveWriteOffPaymentHistorySI")
                      
public class F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpPortImpl implements F09RetrieveWriteOffPaymentHistorySI {

    private static final Logger LOG = Logger.getLogger(F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see f09_writeoffpaymenthistoryinquirypos.f09_retrievewriteoffpaymenthistorysi.F09RetrieveWriteOffPaymentHistorySI#retrieveWriteOffPaymentInfo(f09_writeoffpaymenthistoryinquirypos.RetrieveWriteOffPaymentRequest  retrieveWriteOffPaymentRequest )*
     */
    public th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.RetrieveWriteOffPaymentResponse retrieveWriteOffPaymentInfo(th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.RetrieveWriteOffPaymentRequest retrieveWriteOffPaymentRequest) {
        LOG.info("Executing operation retrieveWriteOffPaymentInfo");
        System.out.println(retrieveWriteOffPaymentRequest);
        try {
            th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.RetrieveWriteOffPaymentResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
