package th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.f09_retrievewriteoffpaymenthistorysi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:18:24.733+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpService", 
                  wsdlLocation = "http://10.32.23.134:7800/F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpService?wsdl",
                  targetNamespace = "http://F09_WriteOffPaymentHistoryInquiryPOS/F09_RetrieveWriteOffPaymentHistorySI") 
public class F09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://F09_WriteOffPaymentHistoryInquiryPOS/F09_RetrieveWriteOffPaymentHistorySI", "F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpService");
    public final static QName F09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpPort = new QName("http://F09_WriteOffPaymentHistoryInquiryPOS/F09_RetrieveWriteOffPaymentHistorySI", "F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.32.23.134:7800/F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(F09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.32.23.134:7800/F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public F09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public F09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public F09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public F09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public F09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public F09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns F09RetrieveWriteOffPaymentHistorySI
     */
    @WebEndpoint(name = "F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpPort")
    public F09RetrieveWriteOffPaymentHistorySI getF09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpPort() {
        return super.getPort(F09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpPort, F09RetrieveWriteOffPaymentHistorySI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns F09RetrieveWriteOffPaymentHistorySI
     */
    @WebEndpoint(name = "F09_RetrieveWriteOffPaymentHistorySIExport1_F09_RetrieveWriteOffPaymentHistorySIHttpPort")
    public F09RetrieveWriteOffPaymentHistorySI getF09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpPort(WebServiceFeature... features) {
        return super.getPort(F09RetrieveWriteOffPaymentHistorySIExport1F09RetrieveWriteOffPaymentHistorySIHttpPort, F09RetrieveWriteOffPaymentHistorySI.class, features);
    }

}
