
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.f13_retrievepaymenthistory.f13_retrievepaymenthistorysi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-31T11:15:16.986+07:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpService",
                      portName = "F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpPort",
                      targetNamespace = "http://F13_RetrievePaymentHistory/F13_RetrievePaymentHistorySI",
                      wsdlLocation = "http://10.32.23.134:7800/F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpService?wsdl",
                      endpointInterface = "th.net.cat.epis.ws.f13_retrievepaymenthistory.f13_retrievepaymenthistorysi.F13RetrievePaymentHistorySI")
                      
public class F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpPortImpl implements th.net.cat.epis.ws.f13_retrievepaymenthistory.f13_retrievepaymenthistorysi.F13RetrievePaymentHistorySI {

    private static final Logger LOG = Logger.getLogger(F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see f13_retrievepaymenthistory.f13_retrievepaymenthistorysi.F13RetrievePaymentHistorySI#retrievePaymentHistory(f13_retrievepaymenthistory.RetrievePaymentHistoryRequest  retrievePaymentHistoryRequest )*
     */
    public th.net.cat.epis.ws.f13_retrievepaymenthistory.RetrievePaymentHistoryResponse retrievePaymentHistory(th.net.cat.epis.ws.f13_retrievepaymenthistory.RetrievePaymentHistoryRequest retrievePaymentHistoryRequest) {
        LOG.info("Executing operation retrievePaymentHistory");
        System.out.println(retrievePaymentHistoryRequest);
        try {
            th.net.cat.epis.ws.f13_retrievepaymenthistory.RetrievePaymentHistoryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
