
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.co.softpos.ws.mg.s001;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-08-02T16:54:33.779+07:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "S001MGInqGiftvoucherService",
                      portName = "S001MGInqGiftvoucherPort",
                      targetNamespace = "http://s001.mg.ws.softpos.co.th/",
                      wsdlLocation = "http://10.44.1.4/InsalePosWS/services/S001MGInqGiftvoucher?wsdl",
                      endpointInterface = "th.co.softpos.ws.mg.s001.S001MGInqGiftvoucher")
                      
public class S001MGInqGiftvoucherPortImpl implements S001MGInqGiftvoucher {

    private static final Logger LOG = Logger.getLogger(S001MGInqGiftvoucherPortImpl.class.getName());

    /* (non-Javadoc)
     * @see th.co.softpos.ws.mg.s001.S001MGInqGiftvoucher#process(th.co.softpos.ws.mg.s001.Request  rq )*
     */
    public th.co.softpos.ws.mg.s001.Response process(th.co.softpos.ws.mg.s001.Request rq) { 
        LOG.info("Executing operation process");
        System.out.println(rq);
        try {
            th.co.softpos.ws.mg.s001.Response _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
