
package th.net.cat.epis.ws.esblibs.inf.esb.f14;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import th.net.cat.epis.ws.esblibs.inf.esb.f14.binding.F14RetrievePaymentSIExport1F14RetrievePaymentSIHttpService;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2559-04-21T09:46:17.732+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class F14RetrievePaymentSI_F14RetrievePaymentSIExport1F14RetrievePaymentSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ESBLibs/INF/ESB/F14/Binding", "F14_RetrievePaymentSIExport1_F14_RetrievePaymentSIHttpService");

    private F14RetrievePaymentSI_F14RetrievePaymentSIExport1F14RetrievePaymentSIHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = F14RetrievePaymentSIExport1F14RetrievePaymentSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        F14RetrievePaymentSIExport1F14RetrievePaymentSIHttpService ss = new F14RetrievePaymentSIExport1F14RetrievePaymentSIHttpService(wsdlURL, SERVICE_NAME);
        F14RetrievePaymentSI port = ss.getF14RetrievePaymentSIExport1F14RetrievePaymentSIHttpPort();  
        
        {
        System.out.println("Invoking retrievePayment...");
        th.net.cat.epis.ws.esblibs.requestresponsecbo.f14.RetrievePaymentRequest _retrievePayment_retrievePaymentRequest = null;
        th.net.cat.epis.ws.esblibs.requestresponsecbo.f14.RetrievePaymentResponse _retrievePayment__return = port.retrievePayment(_retrievePayment_retrievePaymentRequest);
        System.out.println("retrievePayment.result=" + _retrievePayment__return);


        }

        System.exit(0);
    }

}
