package th.net.cat.epis.ws.f11_reversewriteoffpos.f11_reversewriteoffsi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:18:48.189+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://F11_ReverseWriteOffPOS/F11_ReverseWriteOffSI", name = "F11_ReverseWriteOffSI")
@XmlSeeAlso({ObjectFactory.class, th.net.cat.epis.ws.f11_reversewriteoffpos.ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class})
public interface F11ReverseWriteOffSI {

    @WebResult(name = "reverseWriteOffResponse", targetNamespace = "")
    @RequestWrapper(localName = "reverseWriteOff", targetNamespace = "http://F11_ReverseWriteOffPOS/F11_ReverseWriteOffSI", className = "th.net.cat.epis.ws.f11_reversewriteoffpos.f11_reversewriteoffsi.ReverseWriteOff")
    @WebMethod
    @ResponseWrapper(localName = "reverseWriteOffResponse", targetNamespace = "http://F11_ReverseWriteOffPOS/F11_ReverseWriteOffSI", className = "th.net.cat.epis.ws.f11_reversewriteoffpos.f11_reversewriteoffsi.ReverseWriteOffResponse")
    public th.net.cat.epis.ws.f11_reversewriteoffpos.ReverseWriteOffResponse reverseWriteOff(
            @WebParam(name = "reverseWriteOffRequest", targetNamespace = "")
                    th.net.cat.epis.ws.f11_reversewriteoffpos.ReverseWriteOffRequest reverseWriteOffRequest
    );
}
