package th.net.cat.epis.ws.f20_retrievesubscrbyinv.f20_retrievesubscrbyinvsi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:19:56.961+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpService", 
                  wsdlLocation = "http://10.32.23.134:7800/F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpService?wsdl",
                  targetNamespace = "http://F20_RetrieveSubscrByInv/F20_RetrieveSubscrByInvSI") 
public class F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://F20_RetrieveSubscrByInv/F20_RetrieveSubscrByInvSI", "F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpService");
    public final static QName F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpPort = new QName("http://F20_RetrieveSubscrByInv/F20_RetrieveSubscrByInvSI", "F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.32.23.134:7800/F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.32.23.134:7800/F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns F20RetrieveSubscrByInvSI
     */
    @WebEndpoint(name = "F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpPort")
    public F20RetrieveSubscrByInvSI getF20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpPort() {
        return super.getPort(F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpPort, F20RetrieveSubscrByInvSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns F20RetrieveSubscrByInvSI
     */
    @WebEndpoint(name = "F20_RetrieveSubscrByInvSIExport1_F20_RetrieveSubscrByInvSIHttpPort")
    public F20RetrieveSubscrByInvSI getF20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpPort(WebServiceFeature... features) {
        return super.getPort(F20RetrieveSubscrByInvSIExport1F20RetrieveSubscrByInvSIHttpPort, F20RetrieveSubscrByInvSI.class, features);
    }

}
