package th.co.softpos.ws.mg.s002;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-08-02T16:54:49.330+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "S002MGUpdGiftvoucherService", 
                  wsdlLocation = "http://10.44.1.4/InsalePosWS/services/S002MGUpdGiftvoucher?wsdl",
                  targetNamespace = "http://s002.mg.ws.softpos.co.th/") 
public class S002MGUpdGiftvoucherService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://s002.mg.ws.softpos.co.th/", "S002MGUpdGiftvoucherService");
    public final static QName S002MGUpdGiftvoucherPort = new QName("http://s002.mg.ws.softpos.co.th/", "S002MGUpdGiftvoucherPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.44.1.4/InsalePosWS/services/S002MGUpdGiftvoucher?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(S002MGUpdGiftvoucherService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.44.1.4/InsalePosWS/services/S002MGUpdGiftvoucher?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public S002MGUpdGiftvoucherService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public S002MGUpdGiftvoucherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public S002MGUpdGiftvoucherService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public S002MGUpdGiftvoucherService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public S002MGUpdGiftvoucherService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public S002MGUpdGiftvoucherService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns S002MGUpdGiftvoucher
     */
    @WebEndpoint(name = "S002MGUpdGiftvoucherPort")
    public S002MGUpdGiftvoucher getS002MGUpdGiftvoucherPort() {
        return super.getPort(S002MGUpdGiftvoucherPort, S002MGUpdGiftvoucher.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns S002MGUpdGiftvoucher
     */
    @WebEndpoint(name = "S002MGUpdGiftvoucherPort")
    public S002MGUpdGiftvoucher getS002MGUpdGiftvoucherPort(WebServiceFeature... features) {
        return super.getPort(S002MGUpdGiftvoucherPort, S002MGUpdGiftvoucher.class, features);
    }

}
