
package th.net.cat.epis.ws.m05_repeatorder.m05_repeatordersi;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:29:43.300+07:00
 * Generated source version: 3.1.6
 * 
 */
 
public class M05RepeatOrderSI_M05RepeatOrderSIExport1M05RepeatOrderSIHttpPort_Server{

    protected M05RepeatOrderSI_M05RepeatOrderSIExport1M05RepeatOrderSIHttpPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpPortImpl();
        String address = "http://10.32.23.134:7800/M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new M05RepeatOrderSI_M05RepeatOrderSIExport1M05RepeatOrderSIHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
