package th.net.cat.epis.ws.m05_repeatorder.m05_repeatordersi;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:29:43.304+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpService", 
                 // wsdlLocation = "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M05_RepeatOrder_M05_RepeatOrderSIExport1.wsdl",
                  targetNamespace = "http://M05_RepeatOrder/M05_RepeatOrderSI") 
public class M05RepeatOrderSIExport1M05RepeatOrderSIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://M05_RepeatOrder/M05_RepeatOrderSI", "M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpService");
    public final static QName M05RepeatOrderSIExport1M05RepeatOrderSIHttpPort = new QName("http://M05_RepeatOrder/M05_RepeatOrderSI", "M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M05_RepeatOrder_M05_RepeatOrderSIExport1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(M05RepeatOrderSIExport1M05RepeatOrderSIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M05_RepeatOrder_M05_RepeatOrderSIExport1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public M05RepeatOrderSIExport1M05RepeatOrderSIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public M05RepeatOrderSIExport1M05RepeatOrderSIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public M05RepeatOrderSIExport1M05RepeatOrderSIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public M05RepeatOrderSIExport1M05RepeatOrderSIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public M05RepeatOrderSIExport1M05RepeatOrderSIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public M05RepeatOrderSIExport1M05RepeatOrderSIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns M05RepeatOrderSI
     */
    @WebEndpoint(name = "M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpPort")
    public M05RepeatOrderSI getM05RepeatOrderSIExport1M05RepeatOrderSIHttpPort() {
        return super.getPort(M05RepeatOrderSIExport1M05RepeatOrderSIHttpPort, M05RepeatOrderSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns M05RepeatOrderSI
     */
    @WebEndpoint(name = "M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpPort")
    public M05RepeatOrderSI getM05RepeatOrderSIExport1M05RepeatOrderSIHttpPort(WebServiceFeature... features) {
        return super.getPort(M05RepeatOrderSIExport1M05RepeatOrderSIHttpPort, M05RepeatOrderSI.class, features);
    }

}
