DROP TABLE EPIS.PAYMENT_SAP_REVERSE_PAY CASCADE CONSTRAINTS;

CREATE TABLE EPIS.PAYMENT_SAP_REVERSE_PAY
(
  CONTRNO                   VARCHAR2(10 BYTE),
  AR_REF                    NUMBER(9),
  PAY_LOCATION              VARCHAR2(4 BYTE),
  PAY_DATE                  VARCHAR2(8 BYTE),
  PAY_AMOUNT                NUMBER(13,2),
  PAY_VAT                   NUMBER(13,2),
  PAY_WT                    NUMBER(13,2),
  GL_ACCOUNT                VARCHAR2(10 BYTE),
  TRADING_PART              VARCHAR2(4 BYTE),
  BUSINESS_AREA             VARCHAR2(4 BYTE),
  BUSINESS_PLACE            VARCHAR2(4 BYTE),
  REGION                    VARCHAR2(7 BYTE),
  PROCESS_DATETIME          VARCHAR2(16 BYTE),
  PRODUCT_CODE              VARCHAR2(15 BYTE),
  LOCATION_NAME             VARCHAR2(16 CHAR),
  BILL_GROUP                VARCHAR2(25 BYTE),
  CCTR                      VARCHAR2(7 BYTE),
  POST_DATE                 VARCHAR2(8 BYTE),
  REFERENCE                 VARCHAR2(20 BYTE),
  PAY_TOTALAMOUNT           NUMBER(13,2),
  TYPE                      VARCHAR2(3 BYTE),
  SUB_PRODUCT_CODE          VARCHAR2(15 BYTE),
  REVENUE_TYPE_CODE         VARCHAR2(10 BYTE),
  CUSTOMER_GROUP            VARCHAR2(10 BYTE),
  REMARK                    VARCHAR2(10 BYTE),
  BILL_TYPE                 VARCHAR2(10 BYTE),
  SERVICE_PRIORITY_PRODUCT  VARCHAR2(20 BYTE),
  REVERSE_ID                VARCHAR2(10 BYTE),
  CHANNEL                   VARCHAR2(3 BYTE),
  REVERSE_DATE              VARCHAR2(8 BYTE),
  REGION_DW                 VARCHAR2(7 BYTE),
  INV_DATE                  VARCHAR2(8 BYTE),
  DUE_DATE                  VARCHAR2(8 BYTE),
  PAY_TYPE                  VARCHAR2(2 BYTE),
  PERIOD                    VARCHAR2(16 BYTE),
  COLLECTION_UNIT           VARCHAR2(7 BYTE),
  COLLECTION_CODE           VARCHAR2(4 BYTE)
)
TABLESPACE EPIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE EPIS.PAYMENT_SAP_WB_CR_DTL CASCADE CONSTRAINTS;

CREATE TABLE EPIS.PAYMENT_SAP_WB_CR_DTL
(
  CONTRNO                   VARCHAR2(10 BYTE),
  AR_REF                    NUMBER(9),
  PAY_LOCATION              VARCHAR2(4 BYTE),
  PAY_DATE                  VARCHAR2(8 BYTE),
  PAY_AMOUNT                NUMBER(13,2),
  PAY_VAT                   NUMBER(13,2),
  PAY_WT                    NUMBER(13,2),
  GL_ACCOUNT                VARCHAR2(10 BYTE),
  TRADING_PART              VARCHAR2(4 BYTE),
  BUSINESS_AREA             VARCHAR2(4 BYTE),
  BUSINESS_PLACE            VARCHAR2(4 BYTE),
  REGION                    VARCHAR2(7 BYTE),
  PROCESS_DATETIME          VARCHAR2(16 BYTE),
  PRODUCT_CODE              VARCHAR2(15 BYTE),
  LOCATION_NAME             VARCHAR2(16 CHAR),
  BILL_GROUP                VARCHAR2(25 BYTE),
  CCTR                      VARCHAR2(7 BYTE),
  POST_DATE                 VARCHAR2(8 BYTE),
  RECEIPT_NO                VARCHAR2(20 BYTE),
  PAY_TOTALAMOUNT           NUMBER(13,2),
  TYPE                      VARCHAR2(3 BYTE),
  SUB_PRODUCT_CODE          VARCHAR2(15 BYTE),
  REVENUE_TYPE_CODE         VARCHAR2(10 BYTE),
  CUSTOMER_GROUP            VARCHAR2(10 BYTE),
  REMARK                    VARCHAR2(10 BYTE),
  BILL_TYPE                 VARCHAR2(10 BYTE),
  SERVICE_PRIORITY_PRODUCT  VARCHAR2(20 BYTE),
  REVERSE_ID                VARCHAR2(10 BYTE),
  REGION_DW                 VARCHAR2(7 BYTE),
  INV_DATE                  VARCHAR2(8 BYTE),
  DUE_DATE                  VARCHAR2(8 BYTE),
  PAY_TYPE                  VARCHAR2(2 BYTE),
  DEFAULT_PROD              VARCHAR2(1 BYTE),
  USAGE_PERIOD              VARCHAR2(16 BYTE),
  COLLECTION_UNIT           VARCHAR2(7 BYTE),
  COLLECTION_CODE           VARCHAR2(4 BYTE)
)
TABLESPACE EPIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP VIEW EPIS.V_INF_PAYMENT_TO_DW;

/* Formatted on 9/19/2016 3:58:12 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW EPIS.V_INF_PAYMENT_TO_DW
(
   CONTRNO,
   AR_REF,
   PAY_LOCATION,
   PAY_DATE,
   PAY_AMOUNT,
   PAY_VAT,
   PAY_WT,
   GL_ACCOUNT,
   TRADING_PART,
   BUSINESS_AREA,
   BUSINESS_PLACE,
   REGION,
   PROCESS_DATETIME,
   PRODUCT_CODE,
   LOCATION_NAME,
   BILL_GROUP,
   CCTR,
   POST_DATE,
   RECEIPT_NO,
   PAY_TOTALAMOUNT,
   TYPE,
   SUB_PRODUCT_CODE,
   REVENUE_TYPE_CODE,
   CUSTOMER_GROUP,
   REMARK,
   BILL_TYPE,
   SERVICE_PRIORITY_PRODUCT,
   REVERSE_ID,
   REGION_DW,
   INV_DATE,
   DUE_DATE,
   PAY_TYPE,
   DEFAULT_PROD,
   USAGE_PERIOD , 
   PAYMENTID,
   RECEIPTID,
   DEDUCTIONNO,
   DEDUCTIONTYPE,
   INVOICENO,
   ACCOUNTNO
)
AS
   SELECT ROWNUM AS CONTRNO,
          ' ' AS AR_REF,
          CORRECEIPT.BRANCHCODE AS PAY_LOCATION,
          CORPAYMENT.PAYMENTDATE AS PAY_DATE,
          CORPAYMENT.TOTALCHARGE AS PAY_AMOUNT,
          CORPAYMENT.VAT AS PAY_VAT,
          TRSDEDUCTION.AMOUNT AS PAY_WT,
          ' ' AS GL_ACCOUNT,
          ' ' AS TRADING_PART,
          ' ' AS BUSINESS_AREA,
          ' ' AS BUSINESS_PLACE,
          ' ' AS REGION,
          ' ' AS PROCESS_DATETIME,
          ' ' AS PRODUCT_CODE,
          ' ' AS LOCATION_NAME,
          TMPACCOUNT.BILLGROUP AS BILL_GROUP,
          ' ' AS CCTR,
          ' ' AS POST_DATE,
          CORRECEIPT.RECEIPTNO AS RECEIPT_NO,
          CORRECEIPT.AMOUNT AS PAY_TOTALAMOUNT,
          ' ' AS TYPE,
          ' ' AS SUB_PRODUCT_CODE,
          ' ' AS REVENUE_TYPE_CODE,
          ' ' AS CUSTOMER_GROUP,
          ' ' AS REMARK,
          ' ' AS BILL_TYPE,
          ' ' AS SERVICE_PRIORITY_PRODUCT,
          ' ' AS REVERSE_ID,
          ' ' AS REGION_DW,
          TMPINVOICE.ISSUEDATE AS INV_DATE,
          TMPINVOICE.DUEDATE AS DUE_DATE,
          CORPAYMENT.PAYMENTTYPE AS PAY_TYPE,
          ' ' AS DEFAULT_PROD,
          TMPINVOICE.BILLCYCLE AS USAGE_PERIOD , 
          CORPAYMENT.PAYMENTID,
          CORRECEIPT.RECEIPTID,
          TRSDEDUCTION.DEDUCTIONNO,
          TRSDEDUCTION.DEDUCTIONTYPE,
          TMPINVOICE.INVOICENO,
          TMPACCOUNT.ACCOUNTNO
     FROM CORPAYMENT,
          CORRECEIPT,
          TRSDEDUCTION,
          TMPINVOICE,
          TMPACCOUNT
    WHERE     (CORPAYMENT.PAYMENTID = CORRECEIPT.PAYMENTID)
          AND (TRSDEDUCTION.PAYMENTID = CORPAYMENT.PAYMENTID)
          AND (TMPACCOUNT.PAYMENTID = CORPAYMENT.PAYMENTID)
          AND (TMPINVOICE.ACCOUNTID = TMPACCOUNT.ACCOUNTID)
          AND (CORRECEIPT.ACCOUNTID = TMPACCOUNT.ACCOUNTID)
          AND (CORRECEIPT.RECEIPTID = TMPINVOICE.RECEIPTID)
          AND (CORRECEIPT.PAYMENTID = TMPINVOICE.PAYMENTID)
          AND (CORRECEIPT.ACCOUNTID = TMPINVOICE.ACCOUNTID)
          AND (TRSDEDUCTION.DEDUCTIONTYPE = '69BIS')
          AND (CORRECEIPT.ATTRIBUTES NOT LIKE '%R');

DROP VIEW EPIS.V_INF_REV_PAYMENT_TO_DW;

/* Formatted on 9/19/2016 3:58:29 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW EPIS.V_INF_REV_PAYMENT_TO_DW
(
   CONTRNO,
   AR_REF,
   PAY_LOCATION,
   PAY_DATE,
   PAY_AMOUNT,
   PAY_VAT,
   PAY_WT,
   GL_ACCOUNT,
   TRADING_PART,
   BUSINESS_AREA,
   BUSINESS_PLACE,
   REGION,
   PROCESS_DATETIME,
   PRODUCT_CODE,
   LOCATION_NAME,
   BILL_GROUP,
   CCTR,
   POST_DATE,
   RECEIPT_NO,
   PAY_TOTALAMOUNT,
   TYPE,
   SUB_PRODUCT_CODE,
   REVENUE_TYPE_CODE,
   CUSTOMER_GROUP,
   REMARK,
   BILL_TYPE,
   SERVICE_PRIORITY_PRODUCT,
   REVERSE_ID,
   REGION_DW,
   INV_DATE,
   DUE_DATE,
   PAY_TYPE,
   PERIOD,
   COLLECTION_UNIT, 
   COLLECTION_CODE,
   CHANNEL, 
   REVERSE_DATE, 
   PAYMENTID,
   RECEIPTID,
   DEDUCTIONNO,
   DEDUCTIONTYPE,
   INVOICENO,
   ACCOUNTNO
)
AS
   SELECT ROWNUM AS CONTRNO,
          ' ' AS AR_REF,
          CORRECEIPT.BRANCHCODE AS PAY_LOCATION,
          CORPAYMENT.PAYMENTDATE AS PAY_DATE,
          CORPAYMENT.TOTALCHARGE AS PAY_AMOUNT,
          CORPAYMENT.VAT AS PAY_VAT,
          TRSDEDUCTION.AMOUNT AS PAY_WT,
          ' ' AS GL_ACCOUNT,
          ' ' AS TRADING_PART,
          ' ' AS BUSINESS_AREA,
          ' ' AS BUSINESS_PLACE,
          ' ' AS REGION,
          ' ' AS PROCESS_DATETIME,
          ' ' AS PRODUCT_CODE,
          ' ' AS LOCATION_NAME,
          TMPACCOUNT.BILLGROUP AS BILL_GROUP,
          ' ' AS CCTR,
          ' ' AS POST_DATE,
          CORRECEIPT.RECEIPTNO AS RECEIPT_NO,
          CORRECEIPT.AMOUNT AS PAY_TOTALAMOUNT,
          ' ' AS TYPE,
          ' ' AS SUB_PRODUCT_CODE,
          ' ' AS REVENUE_TYPE_CODE,
          ' ' AS CUSTOMER_GROUP,
          ' ' AS REMARK,
          ' ' AS BILL_TYPE,
          ' ' AS SERVICE_PRIORITY_PRODUCT,
          ' ' AS REVERSE_ID,
          ' ' AS REGION_DW,
          TMPINVOICE.ISSUEDATE AS INV_DATE,
          TMPINVOICE.DUEDATE AS DUE_DATE,
          CORPAYMENT.PAYMENTTYPE AS PAY_TYPE,
          TMPINVOICE.BILLCYCLE AS PERIOD,
          ' ' AS COLLECTION_UNIT, 
          ' ' AS COLLECTION_CODE,
          ' ' AS CHANNEL, 
          ' ' AS REVERSE_DATE, 
          CORPAYMENT.PAYMENTID,
          CORRECEIPT.RECEIPTID,
          TRSDEDUCTION.DEDUCTIONNO,
          TRSDEDUCTION.DEDUCTIONTYPE,
          TMPINVOICE.INVOICENO,
          TMPACCOUNT.ACCOUNTNO
     FROM CORPAYMENT,
          CORRECEIPT,
          TRSDEDUCTION,
          TMPINVOICE,
          TMPACCOUNT
    WHERE     (CORPAYMENT.PAYMENTID = CORRECEIPT.PAYMENTID)
          AND (TRSDEDUCTION.PAYMENTID = CORPAYMENT.PAYMENTID)
          AND (TMPACCOUNT.PAYMENTID = CORPAYMENT.PAYMENTID)
          AND (TMPINVOICE.ACCOUNTID = TMPACCOUNT.ACCOUNTID)
          AND (CORRECEIPT.ACCOUNTID = TMPACCOUNT.ACCOUNTID)
          AND (CORRECEIPT.RECEIPTID = TMPINVOICE.RECEIPTID)
          AND (CORRECEIPT.PAYMENTID = TMPINVOICE.PAYMENTID)
          AND (CORRECEIPT.ACCOUNTID = TMPINVOICE.ACCOUNTID)
          AND (TRSDEDUCTION.DEDUCTIONTYPE = '69BIS')
          AND (CORRECEIPT.ATTRIBUTES LIKE '%R');

commit;
