package th.net.cat.epis.ws.m03_createreceipt.m03_createreceiptsi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:28:56.446+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://M03_CreateReceipt/M03_CreateReceiptSI", name = "M03_CreateReceiptSI")
@XmlSeeAlso({th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class, ObjectFactory.class, th.net.cat.epis.ws.m03_createreceipt.ObjectFactory.class})
public interface M03CreateReceiptSI {

    @WebResult(name = "createReceiptResponse", targetNamespace = "")
    @RequestWrapper(localName = "createReceiptInfo", targetNamespace = "http://M03_CreateReceipt/M03_CreateReceiptSI", className = "th.net.cat.epis.ws.m03_createreceipt.m03_createreceiptsi.CreateReceiptInfo")
    @WebMethod
    @ResponseWrapper(localName = "createReceiptInfoResponse", targetNamespace = "http://M03_CreateReceipt/M03_CreateReceiptSI", className = "th.net.cat.epis.ws.m03_createreceipt.m03_createreceiptsi.CreateReceiptInfoResponse")
    public th.net.cat.epis.ws.m03_createreceipt.CreateReceiptResponse createReceiptInfo(
            @WebParam(name = "createReceiptRequest", targetNamespace = "")
                    th.net.cat.epis.ws.m03_createreceipt.CreateReceiptRequest createReceiptRequest
    );
}
