
package th.net.cat.epis.ws.m03_createreceipt.m03_createreceiptsi;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:28:56.454+07:00
 * Generated source version: 3.1.6
 * 
 */
 
public class M03CreateReceiptSI_M03CreateReceiptSIExport1M03CreateReceiptSIHttpPort_Server{

    protected M03CreateReceiptSI_M03CreateReceiptSIExport1M03CreateReceiptSIHttpPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpPortImpl();
        String address = "http://10.32.23.134:7800/M03_CreateReceiptSIExport1_M03_CreateReceiptSIHttpService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new M03CreateReceiptSI_M03CreateReceiptSIExport1M03CreateReceiptSIHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
