package th.net.cat.epis.ws.m01_findorder.m01_findordersi;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:27:09.727+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "M01_FindOrderSIExport1_M01_FindOrderSIHttpService", 
                //  wsdlLocation = "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M01_FindOrder_M01_FindOrderSIExport1.wsdl",
                  targetNamespace = "http://M01_FindOrder/M01_FindOrderSI") 
public class M01FindOrderSIExport1M01FindOrderSIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://M01_FindOrder/M01_FindOrderSI", "M01_FindOrderSIExport1_M01_FindOrderSIHttpService");
    public final static QName M01FindOrderSIExport1M01FindOrderSIHttpPort = new QName("http://M01_FindOrder/M01_FindOrderSI", "M01_FindOrderSIExport1_M01_FindOrderSIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M01_FindOrder_M01_FindOrderSIExport1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(M01FindOrderSIExport1M01FindOrderSIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M01_FindOrder_M01_FindOrderSIExport1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public M01FindOrderSIExport1M01FindOrderSIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public M01FindOrderSIExport1M01FindOrderSIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public M01FindOrderSIExport1M01FindOrderSIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public M01FindOrderSIExport1M01FindOrderSIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public M01FindOrderSIExport1M01FindOrderSIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public M01FindOrderSIExport1M01FindOrderSIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns M01FindOrderSI
     */
    @WebEndpoint(name = "M01_FindOrderSIExport1_M01_FindOrderSIHttpPort")
    public M01FindOrderSI getM01FindOrderSIExport1M01FindOrderSIHttpPort() {
        return super.getPort(M01FindOrderSIExport1M01FindOrderSIHttpPort, M01FindOrderSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns M01FindOrderSI
     */
    @WebEndpoint(name = "M01_FindOrderSIExport1_M01_FindOrderSIHttpPort")
    public M01FindOrderSI getM01FindOrderSIExport1M01FindOrderSIHttpPort(WebServiceFeature... features) {
        return super.getPort(M01FindOrderSIExport1M01FindOrderSIHttpPort, M01FindOrderSI.class, features);
    }

}
