package th.net.cat.epis.ws.m01_findorder.m01_findordersi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:27:09.716+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://M01_FindOrder/M01_FindOrderSI", name = "M01_FindOrderSI")
@XmlSeeAlso({ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class, th.net.cat.epis.ws.m01_findorder.ObjectFactory.class})
public interface M01FindOrderSI {

    @WebResult(name = "findOrderDetailResponse", targetNamespace = "")
    @RequestWrapper(localName = "findOrderInfo", targetNamespace = "http://M01_FindOrder/M01_FindOrderSI", className = "th.net.cat.epis.ws.m01_findorder.m01_findordersi.FindOrderInfo")
    @WebMethod
    @ResponseWrapper(localName = "findOrderInfoResponse", targetNamespace = "http://M01_FindOrder/M01_FindOrderSI", className = "th.net.cat.epis.ws.m01_findorder.m01_findordersi.FindOrderInfoResponse")
    public th.net.cat.epis.ws.m01_findorder.FindOrderResponse findOrderInfo(
            @WebParam(name = "findOrderDetailRequest", targetNamespace = "")
                    th.net.cat.epis.ws.m01_findorder.FindOrderRequest findOrderDetailRequest
    );
}
