
package th.net.cat.epis.ws.m01_findorder.m01_findordersi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:27:09.683+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class M01FindOrderSI_M01FindOrderSIExport1M01FindOrderSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://M01_FindOrder/M01_FindOrderSI", "M01_FindOrderSIExport1_M01_FindOrderSIHttpService");

    private M01FindOrderSI_M01FindOrderSIExport1M01FindOrderSIHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = M01FindOrderSIExport1M01FindOrderSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        M01FindOrderSIExport1M01FindOrderSIHttpService ss = new M01FindOrderSIExport1M01FindOrderSIHttpService(wsdlURL, SERVICE_NAME);
        M01FindOrderSI port = ss.getM01FindOrderSIExport1M01FindOrderSIHttpPort();  
        
        {
        System.out.println("Invoking findOrderInfo...");
            th.net.cat.epis.ws.m01_findorder.FindOrderRequest _findOrderInfo_findOrderDetailRequest = null;
            th.net.cat.epis.ws.m01_findorder.FindOrderResponse _findOrderInfo__return = port.findOrderInfo(_findOrderInfo_findOrderDetailRequest);
        System.out.println("findOrderInfo.result=" + _findOrderInfo__return);


        }

        System.exit(0);
    }

}
