
package th.net.cat.epis.ws.m04_reversereceipt.m04_reversereceiptsi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:29:28.629+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class M04ReverseReceiptSI_M04ReverseReceiptSIExport1M04ReverseReceiptSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://M04_ReverseReceipt/M04_ReverseReceiptSI", "M04_ReverseReceiptSIExport1_M04_ReverseReceiptSIHttpService");

    private M04ReverseReceiptSI_M04ReverseReceiptSIExport1M04ReverseReceiptSIHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = M04ReverseReceiptSIExport1M04ReverseReceiptSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        M04ReverseReceiptSIExport1M04ReverseReceiptSIHttpService ss = new M04ReverseReceiptSIExport1M04ReverseReceiptSIHttpService(wsdlURL, SERVICE_NAME);
        M04ReverseReceiptSI port = ss.getM04ReverseReceiptSIExport1M04ReverseReceiptSIHttpPort();  
        
        {
        System.out.println("Invoking reverseReceiptInfo...");
            th.net.cat.epis.ws.m04_reversereceipt.ReverseReceiptRequest _reverseReceiptInfo_reverseReceiptRequest = null;
            th.net.cat.epis.ws.m04_reversereceipt.ReverseReceiptResponse _reverseReceiptInfo__return = port.reverseReceiptInfo(_reverseReceiptInfo_reverseReceiptRequest);
        System.out.println("reverseReceiptInfo.result=" + _reverseReceiptInfo__return);


        }

        System.exit(0);
    }

}
