package th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.f09_retrievewriteoffpaymenthistorysi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:18:24.725+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://F09_WriteOffPaymentHistoryInquiryPOS/F09_RetrieveWriteOffPaymentHistorySI", name = "F09_RetrieveWriteOffPaymentHistorySI")
@XmlSeeAlso({ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class, th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.ObjectFactory.class})
public interface F09RetrieveWriteOffPaymentHistorySI {

    @WebResult(name = "retrieveWriteOffPaymentResponse", targetNamespace = "")
    @RequestWrapper(localName = "retrieveWriteOffPaymentInfo", targetNamespace = "http://F09_WriteOffPaymentHistoryInquiryPOS/F09_RetrieveWriteOffPaymentHistorySI", className = "th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.f09_retrievewriteoffpaymenthistorysi.RetrieveWriteOffPaymentInfo")
    @WebMethod
    @ResponseWrapper(localName = "retrieveWriteOffPaymentInfoResponse", targetNamespace = "http://F09_WriteOffPaymentHistoryInquiryPOS/F09_RetrieveWriteOffPaymentHistorySI", className = "th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.f09_retrievewriteoffpaymenthistorysi.RetrieveWriteOffPaymentInfoResponse")
    public th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.RetrieveWriteOffPaymentResponse retrieveWriteOffPaymentInfo(
            @WebParam(name = "retrieveWriteOffPaymentRequest", targetNamespace = "")
                    th.net.cat.epis.ws.f09_writeoffpaymenthistoryinquirypos.RetrieveWriteOffPaymentRequest retrieveWriteOffPaymentRequest
    );
}
