package th.net.cat.epis.ws.f19_retrieveaccount.f19_retrieveaccountsi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:19:49.065+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://F19_RetrieveAccount/F19_RetrieveAccountSI", name = "F19_RetrieveAccountSI")
@XmlSeeAlso({th.net.cat.epis.ws.f19_retrieveaccount.ObjectFactory.class, ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class})
public interface F19RetrieveAccountSI {

    @WebResult(name = "retrieveAccountResponse", targetNamespace = "")
    @RequestWrapper(localName = "retrieveAccountInfo", targetNamespace = "http://F19_RetrieveAccount/F19_RetrieveAccountSI", className = "th.net.cat.epis.ws.f19_retrieveaccount.f19_retrieveaccountsi.RetrieveAccountInfo")
    @WebMethod
    @ResponseWrapper(localName = "retrieveAccountInfoResponse", targetNamespace = "http://F19_RetrieveAccount/F19_RetrieveAccountSI", className = "th.net.cat.epis.ws.f19_retrieveaccount.f19_retrieveaccountsi.RetrieveAccountInfoResponse")
    public th.net.cat.epis.ws.f19_retrieveaccount.RetrieveAccountResponse retrieveAccountInfo(
            @WebParam(name = "retrieveAccountRequest", targetNamespace = "")
                    th.net.cat.epis.ws.f19_retrieveaccount.RetrieveAccountRequest retrieveAccountRequest
    );
}
