package th.net.cat.epis.ws.m04_reversereceipt.m04_reversereceiptsi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:29:28.666+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://M04_ReverseReceipt/M04_ReverseReceiptSI", name = "M04_ReverseReceiptSI")
@XmlSeeAlso({ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class, th.net.cat.epis.ws.m04_reversereceipt.ObjectFactory.class})
public interface M04ReverseReceiptSI {

    @WebResult(name = "reverseReceiptResponse", targetNamespace = "")
    @RequestWrapper(localName = "reverseReceiptInfo", targetNamespace = "http://M04_ReverseReceipt/M04_ReverseReceiptSI", className = "th.net.cat.epis.ws.m04_reversereceipt.m04_reversereceiptsi.ReverseReceiptInfo")
    @WebMethod
    @ResponseWrapper(localName = "reverseReceiptInfoResponse", targetNamespace = "http://M04_ReverseReceipt/M04_ReverseReceiptSI", className = "th.net.cat.epis.ws.m04_reversereceipt.m04_reversereceiptsi.ReverseReceiptInfoResponse")
    public th.net.cat.epis.ws.m04_reversereceipt.ReverseReceiptResponse reverseReceiptInfo(
            @WebParam(name = "reverseReceiptRequest", targetNamespace = "")
                    th.net.cat.epis.ws.m04_reversereceipt.ReverseReceiptRequest reverseReceiptRequest
    );
}
