
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.f02_retrieveinvoiceaccountcodesi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:17:12.450+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "F02_RetrieveInvoiceAccountCodeSIExport1_F02_RetrieveInvoiceAccountCodeSIHttpService",
                      portName = "F02_RetrieveInvoiceAccountCodeSIExport1_F02_RetrieveInvoiceAccountCodeSIHttpPort",
                      targetNamespace = "http://F02_RetrieveInvoiceAccountCode/F02_RetrieveInvoiceAccountCodeSI",
                      wsdlLocation = "http://10.32.23.134:7800/F02_RetrieveInvoiceAccountCodeSIExport1_F02_RetrieveInvoiceAccountCodeSIHttpService?wsdl",
                      endpointInterface = "th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.f02_retrieveinvoiceaccountcodesi.F02RetrieveInvoiceAccountCodeSI")
                      
public class F02_RetrieveInvoiceAccountCodeSIExport1_F02_RetrieveInvoiceAccountCodeSIHttpPortImpl implements F02RetrieveInvoiceAccountCodeSI {

    private static final Logger LOG = Logger.getLogger(F02_RetrieveInvoiceAccountCodeSIExport1_F02_RetrieveInvoiceAccountCodeSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see f02_retrieveinvoiceaccountcode.f02_retrieveinvoiceaccountcodesi.F02RetrieveInvoiceAccountCodeSI#retrieveInvoiceAccountCodeInfo(f02_retrieveinvoiceaccountcode.RetrieveInvoiceAccountCodeRequest  retrieveInvoiceAccountCodeRequest )*
     */
    public th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.RetrieveInvoiceAccountCodeResponse retrieveInvoiceAccountCodeInfo(th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.RetrieveInvoiceAccountCodeRequest retrieveInvoiceAccountCodeRequest) {
        LOG.info("Executing operation retrieveInvoiceAccountCodeInfo");
        System.out.println(retrieveInvoiceAccountCodeRequest);
        try {
            th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.RetrieveInvoiceAccountCodeResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
