package th.net.cat.epis.ws.f18_createrefund.f18_createrefundsi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:19:39.537+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://F18_CreateRefund/F18_CreateRefundSI", name = "F18_CreateRefundSI")
@XmlSeeAlso({ObjectFactory.class, th.net.cat.epis.ws.f18_createrefund.ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class})
public interface F18CreateRefundSI {

    @WebResult(name = "createRefundResponse", targetNamespace = "")
    @RequestWrapper(localName = "createRefund", targetNamespace = "http://F18_CreateRefund/F18_CreateRefundSI", className = "th.net.cat.epis.ws.f18_createrefund.f18_createrefundsi.CreateRefund")
    @WebMethod
    @ResponseWrapper(localName = "createRefundResponse", targetNamespace = "http://F18_CreateRefund/F18_CreateRefundSI", className = "th.net.cat.epis.ws.f18_createrefund.f18_createrefundsi.CreateRefundResponse")
    public th.net.cat.epis.ws.f18_createrefund.CreateRefundResponse createRefund(
            @WebParam(name = "createRefundRequest", targetNamespace = "")
                    th.net.cat.epis.ws.f18_createrefund.CreateRefundRequest createRefundRequest
    );
}
