
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.f10_createwriteoffpos.f10_createwriteoffsi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:18:36.874+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "F10_CreateWriteOffSIExport1_F10_CreateWriteOffSIHttpService",
                      portName = "F10_CreateWriteOffSIExport1_F10_CreateWriteOffSIHttpPort",
                      targetNamespace = "http://F10_CreateWriteOffPOS/F10_CreateWriteOffSI",
                      wsdlLocation = "http://10.32.23.134:7800/F10_CreateWriteOffSIExport1_F10_CreateWriteOffSIHttpService?wsdl",
                      endpointInterface = "th.net.cat.epis.ws.f10_createwriteoffpos.f10_createwriteoffsi.F10CreateWriteOffSI")
                      
public class F10_CreateWriteOffSIExport1_F10_CreateWriteOffSIHttpPortImpl implements F10CreateWriteOffSI {

    private static final Logger LOG = Logger.getLogger(F10_CreateWriteOffSIExport1_F10_CreateWriteOffSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see f10_createwriteoffpos.f10_createwriteoffsi.F10CreateWriteOffSI#createWriteOff(f10_createwriteoffpos.CreateWriteOffRequest  createWriteOffRequest )*
     */
    public th.net.cat.epis.ws.f10_createwriteoffpos.CreateWriteOffResponse createWriteOff(th.net.cat.epis.ws.f10_createwriteoffpos.CreateWriteOffRequest createWriteOffRequest) {
        LOG.info("Executing operation createWriteOff");
        System.out.println(createWriteOffRequest);
        try {
            th.net.cat.epis.ws.f10_createwriteoffpos.CreateWriteOffResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
