
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.m04_reversereceipt.m04_reversereceiptsi;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:29:28.653+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "M04_ReverseReceiptSIExport1_M04_ReverseReceiptSIHttpService",
                      portName = "M04_ReverseReceiptSIExport1_M04_ReverseReceiptSIHttpPort",
                      targetNamespace = "http://M04_ReverseReceipt/M04_ReverseReceiptSI",
                    //  wsdlLocation = "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M04_ReverseReceipt_M04_ReverseReceiptSIExport1.wsdl",
                      endpointInterface = "th.net.cat.epis.ws.m04_reversereceipt.m04_reversereceiptsi.M04ReverseReceiptSI")
                      
public class M04_ReverseReceiptSIExport1_M04_ReverseReceiptSIHttpPortImpl implements M04ReverseReceiptSI {

    private static final Logger LOG = Logger.getLogger(M04_ReverseReceiptSIExport1_M04_ReverseReceiptSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see m04_reversereceipt.m04_reversereceiptsi.M04ReverseReceiptSI#reverseReceiptInfo(m04_reversereceipt.ReverseReceiptRequest  reverseReceiptRequest )*
     */
    public th.net.cat.epis.ws.m04_reversereceipt.ReverseReceiptResponse reverseReceiptInfo(th.net.cat.epis.ws.m04_reversereceipt.ReverseReceiptRequest reverseReceiptRequest) {
        LOG.info("Executing operation reverseReceiptInfo");
        System.out.println(reverseReceiptRequest);
        try {
            th.net.cat.epis.ws.m04_reversereceipt.ReverseReceiptResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
