
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.co.softpos.ws.mg.s004;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-08-03T15:13:47.648+07:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "S004MGUpdFreeService",
                      portName = "S004MGUpdFreePort",
                      targetNamespace = "http://s004.mg.ws.softpos.co.th/",
                      wsdlLocation = "http://10.44.1.4/InsalePosWS/services/S004MGUpdFree?wsdl",
                      endpointInterface = "th.co.softpos.ws.mg.s004.S004MGUpdFree")
                      
public class S004MGUpdFreePortImpl implements S004MGUpdFree {

    private static final Logger LOG = Logger.getLogger(S004MGUpdFreePortImpl.class.getName());

    /* (non-Javadoc)
     * @see th.co.softpos.ws.mg.s004.S004MGUpdFree#process(th.co.softpos.ws.mg.s004.Request  rq )*
     */
    public th.co.softpos.ws.mg.s004.Response process(th.co.softpos.ws.mg.s004.Request rq) { 
        LOG.info("Executing operation process");
        System.out.println(rq);
        try {
            th.co.softpos.ws.mg.s004.Response _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
