package th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.f02_retrieveinvoiceaccountcodesi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:17:12.463+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://F02_RetrieveInvoiceAccountCode/F02_RetrieveInvoiceAccountCodeSI", name = "F02_RetrieveInvoiceAccountCodeSI")
@XmlSeeAlso({th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class, ObjectFactory.class})
public interface F02RetrieveInvoiceAccountCodeSI {

    @WebResult(name = "retrieveInvoiceAccountCodeResponse", targetNamespace = "")
    @RequestWrapper(localName = "retrieveInvoiceAccountCodeInfo", targetNamespace = "http://F02_RetrieveInvoiceAccountCode/F02_RetrieveInvoiceAccountCodeSI", className = "th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.f02_retrieveinvoiceaccountcodesi.RetrieveInvoiceAccountCodeInfo")
    @WebMethod
    @ResponseWrapper(localName = "retrieveInvoiceAccountCodeInfoResponse", targetNamespace = "http://F02_RetrieveInvoiceAccountCode/F02_RetrieveInvoiceAccountCodeSI", className = "th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.f02_retrieveinvoiceaccountcodesi.RetrieveInvoiceAccountCodeInfoResponse")
    public th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.RetrieveInvoiceAccountCodeResponse retrieveInvoiceAccountCodeInfo(
            @WebParam(name = "retrieveInvoiceAccountCodeRequest", targetNamespace = "")
                    th.net.cat.epis.ws.f02_retrieveinvoiceaccountcode.RetrieveInvoiceAccountCodeRequest retrieveInvoiceAccountCodeRequest
    );
}
