
package th.net.cat.epis.ws.f03_retrieveinvoicecharges.f03_retrieveinvoicechargessi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:17:23.316+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class F03RetrieveInvoiceChargesSI_F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://F03_RetrieveInvoiceCharges/F03_RetrieveInvoiceChargesSI", "F03_RetrieveInvoiceChargesSIExport1_F03_RetrieveInvoiceChargesSIHttpService");

    private F03RetrieveInvoiceChargesSI_F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpService ss = new F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpService(wsdlURL, SERVICE_NAME);
        F03RetrieveInvoiceChargesSI port = ss.getF03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpPort();  
        
        {
        System.out.println("Invoking retrieveInvoiceChargeInfo...");
            th.net.cat.epis.ws.f03_retrieveinvoicecharges.RetrieveInvoiceChargeInfoRequest _retrieveInvoiceChargeInfo_retrieveInvoiceChargeInfoRequest = null;
            th.net.cat.epis.ws.f03_retrieveinvoicecharges.RetrieveInvoiceChargeInfoResponse _retrieveInvoiceChargeInfo__return = port.retrieveInvoiceChargeInfo(_retrieveInvoiceChargeInfo_retrieveInvoiceChargeInfoRequest);
        System.out.println("retrieveInvoiceChargeInfo.result=" + _retrieveInvoiceChargeInfo__return);


        }

        System.exit(0);
    }

}
