
package th.net.cat.epis.ws.m05_repeatorder.m05_repeatordersi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:29:43.260+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class M05RepeatOrderSI_M05RepeatOrderSIExport1M05RepeatOrderSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://M05_RepeatOrder/M05_RepeatOrderSI", "M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpService");

    private M05RepeatOrderSI_M05RepeatOrderSIExport1M05RepeatOrderSIHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = M05RepeatOrderSIExport1M05RepeatOrderSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        M05RepeatOrderSIExport1M05RepeatOrderSIHttpService ss = new M05RepeatOrderSIExport1M05RepeatOrderSIHttpService(wsdlURL, SERVICE_NAME);
        M05RepeatOrderSI port = ss.getM05RepeatOrderSIExport1M05RepeatOrderSIHttpPort();  
        
        {
        System.out.println("Invoking repeatOrderInfo...");
            th.net.cat.epis.ws.m05_repeatorder.RepeatOrderRequest _repeatOrderInfo_repeatOrderRequest = null;
            th.net.cat.epis.ws.m05_repeatorder.RepeatOrderResponse _repeatOrderInfo__return = port.repeatOrderInfo(_repeatOrderInfo_repeatOrderRequest);
        System.out.println("repeatOrderInfo.result=" + _repeatOrderInfo__return);


        }

        System.exit(0);
    }

}
