package th.net.cat.epis.ws.esblibs.inf.esb.f14;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2559-04-21T09:46:17.806+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://ESBLibs/INF/ESB/F14", name = "F14_RetrievePaymentSI")
@XmlSeeAlso({ObjectFactory.class, th.net.cat.epis.ws.esblibs.requestresponsecbo.f14.ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class})
public interface F14RetrievePaymentSI {

    @WebMethod
    @RequestWrapper(localName = "retrievePayment", targetNamespace = "http://ESBLibs/INF/ESB/F14", className = "th.net.cat.epis.ws.esblibs.inf.esb.f14.RetrievePayment")
    @ResponseWrapper(localName = "retrievePaymentResponse", targetNamespace = "http://ESBLibs/INF/ESB/F14", className = "th.net.cat.epis.ws.esblibs.inf.esb.f14.RetrievePaymentResponse")
    @WebResult(name = "retrievePaymentResponse", targetNamespace = "")
    public th.net.cat.epis.ws.esblibs.requestresponsecbo.f14.RetrievePaymentResponse retrievePayment(
        @WebParam(name = "retrievePaymentRequest", targetNamespace = "")
        th.net.cat.epis.ws.esblibs.requestresponsecbo.f14.RetrievePaymentRequest retrievePaymentRequest
    );
    
    @WebMethod
    @RequestWrapper(localName = "retrievePaymentList", targetNamespace = "http://ESBLibs/INF/ESB/F14", className = "th.net.cat.epis.ws.esblibs.inf.esb.f14.RetrievePaymentList")
    @ResponseWrapper(localName = "retrievePaymentListResponse", targetNamespace = "http://ESBLibs/INF/ESB/F14", className = "th.net.cat.epis.ws.esblibs.inf.esb.f14.RetrievePaymentListResponse")
    @WebResult(name = "retrievePaymentListResponse", targetNamespace = "")
    public th.net.cat.epis.ws.esblibs.requestresponsecbo.f14.RetrievePaymentListResponse retrievePaymentList(
        @WebParam(name = "retrievePaymentListRequest", targetNamespace = "")
        th.net.cat.epis.ws.esblibs.requestresponsecbo.f14.RetrievePaymentListRequest retrievePaymentListRequest
    );
}
