package th.net.cat.epis.ws.f11_reversewriteoffpos.f11_reversewriteoffsi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:18:48.198+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpService", 
                  wsdlLocation = "http://10.32.23.134:7800/F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpService?wsdl",
                  targetNamespace = "http://F11_ReverseWriteOffPOS/F11_ReverseWriteOffSI") 
public class F11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://F11_ReverseWriteOffPOS/F11_ReverseWriteOffSI", "F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpService");
    public final static QName F11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpPort = new QName("http://F11_ReverseWriteOffPOS/F11_ReverseWriteOffSI", "F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.32.23.134:7800/F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(F11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.32.23.134:7800/F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public F11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public F11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public F11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public F11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public F11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public F11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns F11ReverseWriteOffSI
     */
    @WebEndpoint(name = "F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpPort")
    public F11ReverseWriteOffSI getF11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpPort() {
        return super.getPort(F11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpPort, F11ReverseWriteOffSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns F11ReverseWriteOffSI
     */
    @WebEndpoint(name = "F11_ReverseWriteOffSIExport1_F11_ReverseWriteOffSIHttpPort")
    public F11ReverseWriteOffSI getF11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpPort(WebServiceFeature... features) {
        return super.getPort(F11ReverseWriteOffSIExport1F11ReverseWriteOffSIHttpPort, F11ReverseWriteOffSI.class, features);
    }

}
