package th.net.cat.epis.ws.f13_retrievepaymenthistory.f13_retrievepaymenthistorysi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-31T11:15:17.014+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpService", 
                  wsdlLocation = "http://10.32.23.134:7800/F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpService?wsdl",
                  targetNamespace = "http://F13_RetrievePaymentHistory/F13_RetrievePaymentHistorySI") 
public class F13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://F13_RetrievePaymentHistory/F13_RetrievePaymentHistorySI", "F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpService");
    public final static QName F13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpPort = new QName("http://F13_RetrievePaymentHistory/F13_RetrievePaymentHistorySI", "F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.32.23.134:7800/F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(F13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.32.23.134:7800/F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public F13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public F13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public F13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public F13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public F13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public F13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns F13RetrievePaymentHistorySI
     */
    @WebEndpoint(name = "F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpPort")
    public th.net.cat.epis.ws.f13_retrievepaymenthistory.f13_retrievepaymenthistorysi.F13RetrievePaymentHistorySI getF13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpPort() {
        return super.getPort(F13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpPort, th.net.cat.epis.ws.f13_retrievepaymenthistory.f13_retrievepaymenthistorysi.F13RetrievePaymentHistorySI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns F13RetrievePaymentHistorySI
     */
    @WebEndpoint(name = "F13_RetrievePaymentHistorySIExport1_F13_RetrievePaymentHistorySIHttpPort")
    public th.net.cat.epis.ws.f13_retrievepaymenthistory.f13_retrievepaymenthistorysi.F13RetrievePaymentHistorySI getF13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpPort(WebServiceFeature... features) {
        return super.getPort(F13RetrievePaymentHistorySIExport1F13RetrievePaymentHistorySIHttpPort, th.net.cat.epis.ws.f13_retrievepaymenthistory.f13_retrievepaymenthistorysi.F13RetrievePaymentHistorySI.class, features);
    }

}
