package th.net.cat.epis.ws.f10_createwriteoffpos.f10_createwriteoffsi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:18:36.886+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://F10_CreateWriteOffPOS/F10_CreateWriteOffSI", name = "F10_CreateWriteOffSI")
@XmlSeeAlso({ObjectFactory.class, th.net.cat.epis.ws.f10_createwriteoffpos.ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class})
public interface F10CreateWriteOffSI {

    @WebResult(name = "createWriteOffResponse", targetNamespace = "")
    @RequestWrapper(localName = "createWriteOff", targetNamespace = "http://F10_CreateWriteOffPOS/F10_CreateWriteOffSI", className = "th.net.cat.epis.ws.f10_createwriteoffpos.f10_createwriteoffsi.CreateWriteOff")
    @WebMethod
    @ResponseWrapper(localName = "createWriteOffResponse", targetNamespace = "http://F10_CreateWriteOffPOS/F10_CreateWriteOffSI", className = "th.net.cat.epis.ws.f10_createwriteoffpos.f10_createwriteoffsi.CreateWriteOffResponse")
    public th.net.cat.epis.ws.f10_createwriteoffpos.CreateWriteOffResponse createWriteOff(
            @WebParam(name = "createWriteOffRequest", targetNamespace = "")
                    th.net.cat.epis.ws.f10_createwriteoffpos.CreateWriteOffRequest createWriteOffRequest
    );
}
