
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.f01_retrieveinvoiceheader.f01_retrieveinvoiceheadersi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:16:54.624+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpService",
                      portName = "F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpPort",
                      targetNamespace = "http://F01_RetrieveInvoiceHeader/F01_RetrieveInvoiceHeaderSI",
                      wsdlLocation = "http://10.32.23.134:7800/F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpService?wsdl",
                      endpointInterface = "th.net.cat.epis.ws.f01_retrieveinvoiceheader.f01_retrieveinvoiceheadersi.F01RetrieveInvoiceHeaderSI")
                      
public class F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpPortImpl implements F01RetrieveInvoiceHeaderSI {

    private static final Logger LOG = Logger.getLogger(F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see f01_retrieveinvoiceheader.f01_retrieveinvoiceheadersi.F01RetrieveInvoiceHeaderSI#retrieveInvoiceHeaderInfo(f01_retrieveinvoiceheader.RetrieveInvoiceHeaderRequest  retrieveInvoiceHeaderRequest )*
     */
    public th.net.cat.epis.ws.f01_retrieveinvoiceheader.RetrieveInvoiceHeaderResponse retrieveInvoiceHeaderInfo(th.net.cat.epis.ws.f01_retrieveinvoiceheader.RetrieveInvoiceHeaderRequest retrieveInvoiceHeaderRequest) {
        LOG.info("Executing operation retrieveInvoiceHeaderInfo");
        System.out.println(retrieveInvoiceHeaderRequest);
        try {
            th.net.cat.epis.ws.f01_retrieveinvoiceheader.RetrieveInvoiceHeaderResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
