package th.net.cat.epis.ws.f01_retrieveinvoiceheader.f01_retrieveinvoiceheadersi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:16:54.644+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpService", 
                  wsdlLocation = "http://10.32.23.134:7800/F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpService?wsdl",
                  targetNamespace = "http://F01_RetrieveInvoiceHeader/F01_RetrieveInvoiceHeaderSI") 
public class F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://F01_RetrieveInvoiceHeader/F01_RetrieveInvoiceHeaderSI", "F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpService");
    public final static QName F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpPort = new QName("http://F01_RetrieveInvoiceHeader/F01_RetrieveInvoiceHeaderSI", "F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.32.23.134:7800/F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.32.23.134:7800/F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns F01RetrieveInvoiceHeaderSI
     */
    @WebEndpoint(name = "F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpPort")
    public F01RetrieveInvoiceHeaderSI getF01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpPort() {
        return super.getPort(F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpPort, F01RetrieveInvoiceHeaderSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns F01RetrieveInvoiceHeaderSI
     */
    @WebEndpoint(name = "F01_RetrieveInvoiceHeaderSIExport1_F01_RetrieveInvoiceHeaderSIHttpPort")
    public F01RetrieveInvoiceHeaderSI getF01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpPort(WebServiceFeature... features) {
        return super.getPort(F01RetrieveInvoiceHeaderSIExport1F01RetrieveInvoiceHeaderSIHttpPort, F01RetrieveInvoiceHeaderSI.class, features);
    }

}
