
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.m05_repeatorder.m05_repeatordersi;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:29:43.281+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpService",
                      portName = "M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpPort",
                      targetNamespace = "http://M05_RepeatOrder/M05_RepeatOrderSI",
                     // wsdlLocation = "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M05_RepeatOrder_M05_RepeatOrderSIExport1.wsdl",
                      endpointInterface = "th.net.cat.epis.ws.m05_repeatorder.m05_repeatordersi.M05RepeatOrderSI")
                      
public class M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpPortImpl implements M05RepeatOrderSI {

    private static final Logger LOG = Logger.getLogger(M05_RepeatOrderSIExport1_M05_RepeatOrderSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see m05_repeatorder.m05_repeatordersi.M05RepeatOrderSI#repeatOrderInfo(m05_repeatorder.RepeatOrderRequest  repeatOrderRequest )*
     */
    public th.net.cat.epis.ws.m05_repeatorder.RepeatOrderResponse repeatOrderInfo(th.net.cat.epis.ws.m05_repeatorder.RepeatOrderRequest repeatOrderRequest) {
        LOG.info("Executing operation repeatOrderInfo");
        System.out.println(repeatOrderRequest);
        try {
            th.net.cat.epis.ws.m05_repeatorder.RepeatOrderResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
