package th.net.cat.epis.ws.m05_repeatorder.m05_repeatordersi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:29:43.293+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://M05_RepeatOrder/M05_RepeatOrderSI", name = "M05_RepeatOrderSI")
@XmlSeeAlso({th.net.cat.epis.ws.m05_repeatorder.ObjectFactory.class, ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class})
public interface M05RepeatOrderSI {

    @WebResult(name = "repeatOrderResponse", targetNamespace = "")
    @RequestWrapper(localName = "repeatOrderInfo", targetNamespace = "http://M05_RepeatOrder/M05_RepeatOrderSI", className = "th.net.cat.epis.ws.m05_repeatorder.m05_repeatordersi.RepeatOrderInfo")
    @WebMethod
    @ResponseWrapper(localName = "repeatOrderInfoResponse", targetNamespace = "http://M05_RepeatOrder/M05_RepeatOrderSI", className = "th.net.cat.epis.ws.m05_repeatorder.m05_repeatordersi.RepeatOrderInfoResponse")
    public th.net.cat.epis.ws.m05_repeatorder.RepeatOrderResponse repeatOrderInfo(
            @WebParam(name = "repeatOrderRequest", targetNamespace = "")
                    th.net.cat.epis.ws.m05_repeatorder.RepeatOrderRequest repeatOrderRequest
    );
}
