package th.net.cat.epis.ws.esblibs.inf.esb.f4.binding;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import th.net.cat.epis.ws.esblibs.inf.esb.f4.F4CreatePaymentSI;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2559-04-21T09:38:58.298+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "F4_CreatePaymentSIExport1_F4_CreatePaymentSIHttpService", 
                  wsdlLocation = "http://10.32.23.134:7800/F4_CreatePaymentSIExport1_F4_CreatePaymentSIHttpService?wsdl",
                  targetNamespace = "http://ESBLibs/INF/ESB/F4/Binding") 
public class F4CreatePaymentSIExport1F4CreatePaymentSIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ESBLibs/INF/ESB/F4/Binding", "F4_CreatePaymentSIExport1_F4_CreatePaymentSIHttpService");
    public final static QName F4CreatePaymentSIExport1F4CreatePaymentSIHttpPort = new QName("http://ESBLibs/INF/ESB/F4/Binding", "F4_CreatePaymentSIExport1_F4_CreatePaymentSIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.32.23.134:7800/F4_CreatePaymentSIExport1_F4_CreatePaymentSIHttpService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(F4CreatePaymentSIExport1F4CreatePaymentSIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.32.23.134:7800/F4_CreatePaymentSIExport1_F4_CreatePaymentSIHttpService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public F4CreatePaymentSIExport1F4CreatePaymentSIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public F4CreatePaymentSIExport1F4CreatePaymentSIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public F4CreatePaymentSIExport1F4CreatePaymentSIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public F4CreatePaymentSIExport1F4CreatePaymentSIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public F4CreatePaymentSIExport1F4CreatePaymentSIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public F4CreatePaymentSIExport1F4CreatePaymentSIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns F4CreatePaymentSI
     */
    @WebEndpoint(name = "F4_CreatePaymentSIExport1_F4_CreatePaymentSIHttpPort")
    public F4CreatePaymentSI getF4CreatePaymentSIExport1F4CreatePaymentSIHttpPort() {
        return super.getPort(F4CreatePaymentSIExport1F4CreatePaymentSIHttpPort, F4CreatePaymentSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns F4CreatePaymentSI
     */
    @WebEndpoint(name = "F4_CreatePaymentSIExport1_F4_CreatePaymentSIHttpPort")
    public F4CreatePaymentSI getF4CreatePaymentSIExport1F4CreatePaymentSIHttpPort(WebServiceFeature... features) {
        return super.getPort(F4CreatePaymentSIExport1F4CreatePaymentSIHttpPort, F4CreatePaymentSI.class, features);
    }

}
