
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.f18_createrefund.f18_createrefundsi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:19:39.524+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "F18_CreateRefundSIExport1_F18_CreateRefundSIHttpService",
                      portName = "F18_CreateRefundSIExport1_F18_CreateRefundSIHttpPort",
                      targetNamespace = "http://F18_CreateRefund/F18_CreateRefundSI",
                      wsdlLocation = "http://10.32.23.134:7800/F18_CreateRefundSIExport1_F18_CreateRefundSIHttpService?wsdl",
                      endpointInterface = "th.net.cat.epis.ws.f18_createrefund.f18_createrefundsi.F18CreateRefundSI")
                      
public class F18_CreateRefundSIExport1_F18_CreateRefundSIHttpPortImpl implements F18CreateRefundSI {

    private static final Logger LOG = Logger.getLogger(F18_CreateRefundSIExport1_F18_CreateRefundSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see f18_createrefund.f18_createrefundsi.F18CreateRefundSI#createRefund(f18_createrefund.CreateRefundRequest  createRefundRequest )*
     */
    public th.net.cat.epis.ws.f18_createrefund.CreateRefundResponse createRefund(th.net.cat.epis.ws.f18_createrefund.CreateRefundRequest createRefundRequest) {
        LOG.info("Executing operation createRefund");
        System.out.println(createRefundRequest);
        try {
            th.net.cat.epis.ws.f18_createrefund.CreateRefundResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
