
package th.net.cat.epis.ws.f18_createrefund.f18_createrefundsi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:19:39.499+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class F18CreateRefundSI_F18CreateRefundSIExport1F18CreateRefundSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://F18_CreateRefund/F18_CreateRefundSI", "F18_CreateRefundSIExport1_F18_CreateRefundSIHttpService");

    private F18CreateRefundSI_F18CreateRefundSIExport1F18CreateRefundSIHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = F18CreateRefundSIExport1F18CreateRefundSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        F18CreateRefundSIExport1F18CreateRefundSIHttpService ss = new F18CreateRefundSIExport1F18CreateRefundSIHttpService(wsdlURL, SERVICE_NAME);
        F18CreateRefundSI port = ss.getF18CreateRefundSIExport1F18CreateRefundSIHttpPort();  
        
        {
        System.out.println("Invoking createRefund...");
            th.net.cat.epis.ws.f18_createrefund.CreateRefundRequest _createRefund_createRefundRequest = null;
            th.net.cat.epis.ws.f18_createrefund.CreateRefundResponse _createRefund__return = port.createRefund(_createRefund_createRefundRequest);
        System.out.println("createRefund.result=" + _createRefund__return);


        }

        System.exit(0);
    }

}
