package th.net.cat.epis.ws.esblibs.inf.esb.f4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2559-04-21T09:38:58.288+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://ESBLibs/INF/ESB/F4", name = "F4_CreatePaymentSI")
@XmlSeeAlso({ObjectFactory.class, th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class, th.net.cat.epis.ws.esblibs.requestresponsecbo.f4.ObjectFactory.class})
public interface F4CreatePaymentSI {

    @WebMethod
    @RequestWrapper(localName = "createPayment", targetNamespace = "http://ESBLibs/INF/ESB/F4", className = "th.net.cat.epis.ws.esblibs.inf.esb.f4.CreatePayment")
    @ResponseWrapper(localName = "createPaymentResponse", targetNamespace = "http://ESBLibs/INF/ESB/F4", className = "th.net.cat.epis.ws.esblibs.inf.esb.f4.CreatePaymentResponse")
    @WebResult(name = "createPaymentResponse", targetNamespace = "")
    public th.net.cat.epis.ws.esblibs.requestresponsecbo.f4.CreatePaymentResponse createPayment(
        @WebParam(name = "createPaymentRequest", targetNamespace = "")
        th.net.cat.epis.ws.esblibs.requestresponsecbo.f4.CreatePaymentRequest createPaymentRequest
    );
}
