
package th.net.cat.epis.ws.f08_writeoffinquirypos.f08_writeoffinquirysi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:18:10.964+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class F08WriteOffInquirySI_F08WriteOffInquirySIExport1F08WriteOffInquirySIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://F08_WriteOffInquiryPOS/F08_WriteOffInquirySI", "F08_WriteOffInquirySIExport1_F08_WriteOffInquirySIHttpService");

    private F08WriteOffInquirySI_F08WriteOffInquirySIExport1F08WriteOffInquirySIHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = F08WriteOffInquirySIExport1F08WriteOffInquirySIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        F08WriteOffInquirySIExport1F08WriteOffInquirySIHttpService ss = new F08WriteOffInquirySIExport1F08WriteOffInquirySIHttpService(wsdlURL, SERVICE_NAME);
        F08WriteOffInquirySI port = ss.getF08WriteOffInquirySIExport1F08WriteOffInquirySIHttpPort();  
        
        {
        System.out.println("Invoking retrieveWriteOffInvoice...");
            th.net.cat.epis.ws.f08_writeoffinquirypos.RetrieveWriteOffInvoiceRequest _retrieveWriteOffInvoice_retrieveWriteOffInvoiceRequest = null;
            th.net.cat.epis.ws.f08_writeoffinquirypos.RetrieveWriteOffInvoiceResponse _retrieveWriteOffInvoice__return = port.retrieveWriteOffInvoice(_retrieveWriteOffInvoice_retrieveWriteOffInvoiceRequest);
        System.out.println("retrieveWriteOffInvoice.result=" + _retrieveWriteOffInvoice__return);


        }

        System.exit(0);
    }

}
