package th.net.cat.epis.ws.f03_retrieveinvoicecharges.f03_retrieveinvoicechargessi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:17:23.361+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "F03_RetrieveInvoiceChargesSIExport1_F03_RetrieveInvoiceChargesSIHttpService", 
                  wsdlLocation = "http://10.32.23.134:7800/F03_RetrieveInvoiceChargesSIExport1_F03_RetrieveInvoiceChargesSIHttpService?wsdl",
                  targetNamespace = "http://F03_RetrieveInvoiceCharges/F03_RetrieveInvoiceChargesSI") 
public class F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://F03_RetrieveInvoiceCharges/F03_RetrieveInvoiceChargesSI", "F03_RetrieveInvoiceChargesSIExport1_F03_RetrieveInvoiceChargesSIHttpService");
    public final static QName F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpPort = new QName("http://F03_RetrieveInvoiceCharges/F03_RetrieveInvoiceChargesSI", "F03_RetrieveInvoiceChargesSIExport1_F03_RetrieveInvoiceChargesSIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.32.23.134:7800/F03_RetrieveInvoiceChargesSIExport1_F03_RetrieveInvoiceChargesSIHttpService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.32.23.134:7800/F03_RetrieveInvoiceChargesSIExport1_F03_RetrieveInvoiceChargesSIHttpService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns F03RetrieveInvoiceChargesSI
     */
    @WebEndpoint(name = "F03_RetrieveInvoiceChargesSIExport1_F03_RetrieveInvoiceChargesSIHttpPort")
    public F03RetrieveInvoiceChargesSI getF03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpPort() {
        return super.getPort(F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpPort, F03RetrieveInvoiceChargesSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns F03RetrieveInvoiceChargesSI
     */
    @WebEndpoint(name = "F03_RetrieveInvoiceChargesSIExport1_F03_RetrieveInvoiceChargesSIHttpPort")
    public F03RetrieveInvoiceChargesSI getF03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpPort(WebServiceFeature... features) {
        return super.getPort(F03RetrieveInvoiceChargesSIExport1F03RetrieveInvoiceChargesSIHttpPort, F03RetrieveInvoiceChargesSI.class, features);
    }

}
