package th.net.cat.epis.ws.f03_retrieveinvoicecharges.f03_retrieveinvoicechargessi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:17:23.353+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://F03_RetrieveInvoiceCharges/F03_RetrieveInvoiceChargesSI", name = "F03_RetrieveInvoiceChargesSI")
@XmlSeeAlso({th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class, th.net.cat.epis.ws.f03_retrieveinvoicecharges.ObjectFactory.class, ObjectFactory.class})
public interface F03RetrieveInvoiceChargesSI {

    @WebResult(name = "retrieveInvoiceChargeInfoResponse", targetNamespace = "")
    @RequestWrapper(localName = "retrieveInvoiceChargeInfo", targetNamespace = "http://F03_RetrieveInvoiceCharges/F03_RetrieveInvoiceChargesSI", className = "th.net.cat.epis.ws.f03_retrieveinvoicecharges.f03_retrieveinvoicechargessi.RetrieveInvoiceChargeInfo")
    @WebMethod
    @ResponseWrapper(localName = "retrieveInvoiceChargeInfoResponse", targetNamespace = "http://F03_RetrieveInvoiceCharges/F03_RetrieveInvoiceChargesSI", className = "th.net.cat.epis.ws.f03_retrieveinvoicecharges.f03_retrieveinvoicechargessi.RetrieveInvoiceChargeInfoResponse")
    public th.net.cat.epis.ws.f03_retrieveinvoicecharges.RetrieveInvoiceChargeInfoResponse retrieveInvoiceChargeInfo(
            @WebParam(name = "retrieveInvoiceChargeInfoRequest", targetNamespace = "")
                    th.net.cat.epis.ws.f03_retrieveinvoicecharges.RetrieveInvoiceChargeInfoRequest retrieveInvoiceChargeInfoRequest
    );
}
