package th.net.cat.epis.ws.f13_retrievepaymenthistory.f13_retrievepaymenthistorysi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-31T11:15:17.001+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://F13_RetrievePaymentHistory/F13_RetrievePaymentHistorySI", name = "F13_RetrievePaymentHistorySI")
@XmlSeeAlso({th.net.cat.epis.ws.esblibs.cbos.ObjectFactory.class, th.net.cat.epis.ws.f13_retrievepaymenthistory.ObjectFactory.class, th.net.cat.epis.ws.f13_retrievepaymenthistory.ObjectFactory.class})
public interface F13RetrievePaymentHistorySI {

    @WebResult(name = "retrievePaymentHistoryResponse", targetNamespace = "")
    @RequestWrapper(localName = "retrievePaymentHistory", targetNamespace = "http://F13_RetrievePaymentHistory/F13_RetrievePaymentHistorySI", className = "th.net.cat.epis.ws.f13_retrievepaymenthistory.f13_retrievepaymenthistorysi.RetrievePaymentHistory")
    @WebMethod
    @ResponseWrapper(localName = "retrievePaymentHistoryResponse", targetNamespace = "http://F13_RetrievePaymentHistory/F13_RetrievePaymentHistorySI", className = "th.net.cat.epis.ws.f13_retrievepaymenthistory.f13_retrievepaymenthistorysi.RetrievePaymentHistoryResponse")
    public th.net.cat.epis.ws.f13_retrievepaymenthistory.RetrievePaymentHistoryResponse retrievePaymentHistory(
        @WebParam(name = "retrievePaymentHistoryRequest", targetNamespace = "")
                th.net.cat.epis.ws.f13_retrievepaymenthistory.RetrievePaymentHistoryRequest retrievePaymentHistoryRequest
    );
}
