
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.f06_reversepayment.f06_reversepaymentsi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:17:54.326+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpService",
                      portName = "F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpPort",
                      targetNamespace = "http://F06_ReversePayment/F06_ReversePaymentSI",
                      wsdlLocation = "http://10.32.23.134:7800/F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpService?wsdl",
                      endpointInterface = "th.net.cat.epis.ws.f06_reversepayment.f06_reversepaymentsi.F06ReversePaymentSI")
                      
public class F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpPortImpl implements F06ReversePaymentSI {

    private static final Logger LOG = Logger.getLogger(F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see f06_reversepayment.f06_reversepaymentsi.F06ReversePaymentSI#reversePayment(f06_reversepayment.ReversePaymentRequest  reversePaymentRequest )*
     */
    public th.net.cat.epis.ws.f06_reversepayment.ReversePaymentResponse reversePayment(th.net.cat.epis.ws.f06_reversepayment.ReversePaymentRequest reversePaymentRequest) {
        LOG.info("Executing operation reversePayment");
        System.out.println(reversePaymentRequest);
        try {
            th.net.cat.epis.ws.f06_reversepayment.ReversePaymentResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
