
package th.net.cat.epis.ws.f06_reversepayment.f06_reversepaymentsi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-24T17:17:54.305+07:00
 * Generated source version: 3.1.6
 * 
 */
public final class F06ReversePaymentSI_F06ReversePaymentSIExport1F06ReversePaymentSIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://F06_ReversePayment/F06_ReversePaymentSI", "F06_ReversePaymentSIExport1_F06_ReversePaymentSIHttpService");

    private F06ReversePaymentSI_F06ReversePaymentSIExport1F06ReversePaymentSIHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = F06ReversePaymentSIExport1F06ReversePaymentSIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        F06ReversePaymentSIExport1F06ReversePaymentSIHttpService ss = new F06ReversePaymentSIExport1F06ReversePaymentSIHttpService(wsdlURL, SERVICE_NAME);
        F06ReversePaymentSI port = ss.getF06ReversePaymentSIExport1F06ReversePaymentSIHttpPort();  
        
        {
        System.out.println("Invoking reversePayment...");
            th.net.cat.epis.ws.f06_reversepayment.ReversePaymentRequest _reversePayment_reversePaymentRequest = null;
            th.net.cat.epis.ws.f06_reversepayment.ReversePaymentResponse _reversePayment__return = port.reversePayment(_reversePayment_reversePaymentRequest);
        System.out.println("reversePayment.result=" + _reversePayment__return);


        }

        System.exit(0);
    }

}
