package th.co.softpos.ws.mg.s004;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-08-03T15:13:47.670+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "S004MGUpdFreeService", 
                  wsdlLocation = "http://10.44.1.4/InsalePosWS/services/S004MGUpdFree?wsdl",
                  targetNamespace = "http://s004.mg.ws.softpos.co.th/") 
public class S004MGUpdFreeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://s004.mg.ws.softpos.co.th/", "S004MGUpdFreeService");
    public final static QName S004MGUpdFreePort = new QName("http://s004.mg.ws.softpos.co.th/", "S004MGUpdFreePort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.44.1.4/InsalePosWS/services/S004MGUpdFree?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(S004MGUpdFreeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.44.1.4/InsalePosWS/services/S004MGUpdFree?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public S004MGUpdFreeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public S004MGUpdFreeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public S004MGUpdFreeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public S004MGUpdFreeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public S004MGUpdFreeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public S004MGUpdFreeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns S004MGUpdFree
     */
    @WebEndpoint(name = "S004MGUpdFreePort")
    public S004MGUpdFree getS004MGUpdFreePort() {
        return super.getPort(S004MGUpdFreePort, S004MGUpdFree.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns S004MGUpdFree
     */
    @WebEndpoint(name = "S004MGUpdFreePort")
    public S004MGUpdFree getS004MGUpdFreePort(WebServiceFeature... features) {
        return super.getPort(S004MGUpdFreePort, S004MGUpdFree.class, features);
    }

}
