
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package th.net.cat.epis.ws.m01_findorder.m01_findordersi;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:27:09.704+07:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "M01_FindOrderSIExport1_M01_FindOrderSIHttpService",
                      portName = "M01_FindOrderSIExport1_M01_FindOrderSIHttpPort",
                      targetNamespace = "http://M01_FindOrder/M01_FindOrderSI",
                      //wsdlLocation = "file:/Users/imake/IdeaProjects/CAT_PROJECT/MNPModule/mnpservices/src/main/webapp/wsdl/MNP/M01_FindOrder_M01_FindOrderSIExport1.wsdl",
                      endpointInterface = "th.net.cat.epis.ws.m01_findorder.m01_findordersi.M01FindOrderSI")
                      
public class M01_FindOrderSIExport1_M01_FindOrderSIHttpPortImpl implements M01FindOrderSI {

    private static final Logger LOG = Logger.getLogger(M01_FindOrderSIExport1_M01_FindOrderSIHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see th.net.cat.epis.ws.m01_findorder.m01_findordersi.M01FindOrderSI#findOrderInfo(m01_findorder.FindOrderRequest  findOrderDetailRequest )*
     */
    public th.net.cat.epis.ws.m01_findorder.FindOrderResponse findOrderInfo(th.net.cat.epis.ws.m01_findorder.FindOrderRequest findOrderDetailRequest) {
        LOG.info("Executing operation findOrderInfo");
        System.out.println(findOrderDetailRequest);
        try {
            th.net.cat.epis.ws.m01_findorder.FindOrderResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
