
package th.net.cat.epis.ws.m01_findorder.m01_findordersi;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-25T23:27:09.723+07:00
 * Generated source version: 3.1.6
 * 
 */
 
public class M01FindOrderSI_M01FindOrderSIExport1M01FindOrderSIHttpPort_Server{

    protected M01FindOrderSI_M01FindOrderSIExport1M01FindOrderSIHttpPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new M01_FindOrderSIExport1_M01_FindOrderSIHttpPortImpl();
        String address = "http://10.32.23.134:7800/M01_FindOrderSIExport1_M01_FindOrderSIHttpService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new M01FindOrderSI_M01FindOrderSIExport1M01FindOrderSIHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
